#!/bin/bash

JOB=batarang
BASE=/var/vcap

export PATH=$BASE/bosh/bin:$PATH
export BUNDLE_GEMFILE=$BASE/packages/$JOB/Gemfile

RUN_DIR=$BASE/sys/run/$JOB
LOG_DIR=$BASE/sys/log/$JOB
BIN_DIR=$BASE/packages/$JOB/bin
STORE_DIR=$BASE/store/$JOB
PIDFILE=$RUN_DIR/$JOB.pid

RUNAS=root

case $1 in

  start)
    mkdir -p $RUN_DIR $LOG_DIR $STORE_DIR
    chown -R $RUNAS:$RUNAS $RUN_DIR $LOG_DIR $STORE_DIR

    echo $$ > $PIDFILE

    export NATS_URI='<%= p("mbus") %>'

    exec chpst -u $RUNAS:$RUNAS \
      bundle exec $BIN_DIR/batarang <%= spec.index %> \
      >>$LOG_DIR/$JOB.stdout.log \
      2>>$LOG_DIR/$JOB.stderr.log
    ;;

  stop)
    PID=$(head -1 $PIDFILE)
    kill $PID
    while [ -e /proc/$PID ]; do sleep 0.1; done
    rm -f $PIDFILE
    ;;

  *)

  echo "Usage: $JOB_ctl {start|stop}" ;;
esac
exit 0

