# Copyright (c) 2009-2012 VMware, Inc.

source :rubygems

gem "bcrypt-ruby"
gem "blobstore_client", "~>0.3.11"
gem "bosh_common", ">=0.4.0"
gem "bosh_cpi", ">=0.4.2"
gem "bosh_aws_cpi", ">=0.3.1"
gem "bosh_vsphere_cpi", ">=0.4.8"
gem "eventmachine"
gem "httpclient"
gem "nats", "=0.4.22.beta.4"
gem "netaddr"
gem "rack-test"         # needed for console
gem "rake"
gem "redis"
gem "resque"
gem "sequel"
gem "sinatra"
gem "SystemTimer", :platforms => :ruby_18
gem "thin"
gem "uuidtools"
gem "yajl-ruby"

group :production do
  gem "pg"
end

group :development do
  gem "guard"
  gem "guard-bundler"
  gem "guard-rspec"
  gem "ruby_gntp"
  gem "ruby-debug", :platforms => :ruby_18
  gem "ruby-debug19", :platforms => :ruby_19
end

group :development, :test do
  gem "sqlite3"
  gem "machinist", "~>1.0"
  gem "minitar"
  gem "ci_reporter"
  gem "rspec"
  gem "rcov", :platforms => :ruby_18
  gem "simplecov", :platforms => :ruby_19
  gem "simplecov-rcov", :platforms => :ruby_19
end
