# Copyright (c) 2009-2012 VMware, Inc.

source :rubygems

gem "bcrypt-ruby"
gem "blobstore_client", "~>0.5.0"
gem "bosh_common", ">=0.5.1"
gem "bosh_encryption", ">=0.0.2"
gem "bosh_cpi", ">=0.4.3"
gem "bosh_aws_cpi", ">=0.6.2"
gem "bosh_openstack_cpi", ">=0.0.4"
gem "bosh_vsphere_cpi", ">=0.5.0"
gem "eventmachine"
gem "httpclient"
gem "nats", "=0.4.22"
gem "netaddr"
gem "rack-test"         # needed for console
gem "rake"
gem "redis"
gem "resque"
gem "sequel"
gem "sinatra"
gem "SystemTimer", :platforms => :ruby_18
gem "thin"
gem "uuidtools"
gem "yajl-ruby"

group :production do
  gem "pg"
end

group :development do
  gem "guard"
  gem "guard-bundler"
  gem "guard-rspec"
  gem "ruby-debug", :platforms => :ruby_18
  gem "ruby-debug19", :platforms => :ruby_19

  require 'rbconfig'

  if RbConfig::CONFIG['target_os'] =~ /darwin/i
    gem 'rb-fsevent', :require => false

    if `uname`.strip == 'Darwin' && `sw_vers -productVersion`.strip >= '10.8'
      gem 'terminal-notifier-guard', '~> 1.5.3', :require => false
    else
      gem 'growl', :require => false
    end rescue Errno::ENOENT

  elsif RbConfig::CONFIG['target_os'] =~ /linux/i
    gem 'libnotify',  '~> 0.8.0', :require => false
    gem 'rb-inotify', :require => false

  elsif RbConfig::CONFIG['target_os'] =~ /mswin|mingw/i
    gem 'win32console', :require => false
    gem 'rb-notifu', '>= 0.0.4', :require => false
    gem 'wdm', :require => false
  end
end

group :development, :test do
  gem "sqlite3"
  gem "machinist", "~>1.0"
  gem "minitar"
  gem "ci_reporter"
  # can't upgrade rspec as we use .and_return with a Proc,
  # which has been removed past version 2.8
  gem "rspec", "=2.8"
  gem "rcov", :platforms => :ruby_18
  gem "simplecov", :platforms => :ruby_19
  gem "simplecov-rcov", :platforms => :ruby_19
end
