source :rubygems

gem 'highline'
gem 'rest-client'
gem "blobstore_client", "~> 0.3"
gem "yajl-ruby", :require => "yajl"
gem "monit_api"

gem "uuidtools"
gem "netaddr"
gem "posix-spawn"

gem 'vmc'

group :test do
  gem "rcov_analyzer"
  gem "rspec", :require => ["spec", "spec/interop/test"]
  gem "rcov"
  gem "ci_reporter"
end
