source :rubygems

#gem 'ncurses'
#gem 'rbcurse'
gem 'highline'
gem 'rest-client'
gem "blobstore_client", "~> 0.3"
gem "yajl-ruby", :require => "yajl"

gem "uuidtools"
gem "netaddr"
gem "posix-spawn"

group :test do
  gem "rcov_analyzer"
  gem "rspec", :require => ["spec", "spec/interop/test"]
  gem "rcov"
  gem "ci_reporter"
end
