source :rubygems

gem 'ncurses'
gem 'rbcurse'
gem 'highline'
gem 'rest-client'
gem "blobstore_client", "~> 0.2"
gem "yajl-ruby", :require => "yajl"

gem "nats"
gem "uuidtools"
gem "netaddr"
gem "posix-spawn"
