source 'https://rubygems.org'

gem 'bosh-core', path: '../bosh-core'
gem 'bosh-director', path: '../bosh-director'
gem 'bosh-stemcell', path: '../bosh-stemcell'
gem 'bosh_cli', path: '../bosh_cli'
gem 'bosh_cli_plugin_aws', path: '../bosh_cli_plugin_aws'
gem 'bosh_common', path: '../bosh_common'
gem 'fakefs', git: 'https://github.com/pivotal-cf-experimental/fakefs.git', ref: 'ebde3d6c'

gemspec
