#!/bin/bash

RUN_DIR=/var/vcap/sys/run/director
LOG_DIR=/var/vcap/sys/log/director
JOB_DIR=/var/vcap/jobs/director
PIDFILE=$RUN_DIR/nginx.pid
STORE_DIR=/var/vcap/store/director/nginx
SSL_DIR=/var/vcap/jobs/director/config/ssl

case $1 in

  start)
    mkdir -p $RUN_DIR $LOG_DIR $STORE_DIR

    echo $$ > $PIDFILE

    # if the properties contain director.ssl.key & director.ssl.cert
    # the two files below will contain key & cert, then copy them to
    # the persistent disk
    if [ -s $SSL_DIR/director.key -a -s $SSL_DIR/director.pem ]; then
      cp $SSL_DIR/* $STORE_DIR
    # otherwise, if the key or cert doesn't exist in the persistent disk
    # create new ones
    elif [ ! -f $STORE_DIR/director.key -o ! -f $STORE_DIR/director.pem ]; then
      openssl req -nodes -new -newkey rsa:2048 -out $STORE_DIR/director.csr \
        -keyout $STORE_DIR/director.key -subj '/O=Bosh/CN=*'
      openssl x509 -req -days 3650 -in $STORE_DIR/director.csr \
        -signkey $STORE_DIR/director.key -out $STORE_DIR/director.pem
    fi

    exec /var/vcap/packages/nginx/sbin/nginx -c $JOB_DIR/config/nginx.conf \
      >>$LOG_DIR/nginx.stdout.log 2>>$LOG_DIR/nginx.stderr.log
    ;;

  stop)
    PID=$(head -1 $PIDFILE)
    kill $PID
    while [ -e /proc/$PID ]; do sleep 0.1; done
    rm -f $PIDFILE
    ;;

  *)
    echo "Usage: nginx_ctl {start|stop}" ;;
esac
exit 0
