#!/bin/sh
#
# This script runs as root through sudo without the need for a password,
# so it needs to make sure it can't be abused.
#

set -u
set -x
set -e

adapter=$1
host=$2
user=$3
pass=$4
db_name=$5
backup_file=$6

db_su=$user

if [ "$host" = '127.0.0.1' ] || [ "$host" = 'localhost' ] || [ "$host" = '::1' ]
then
    db_su=vcap
fi

PATH=/var/vcap/bosh/bin:$PATH

REGISTRY_EXISTS=false

for i in $(seq 60)
do
    if ! monit summary | grep -q ' pending$' ; then
        break
    fi

    sleep 5
done

if monit summary | grep -q registry ; then
  REGISTRY_EXISTS=true
fi

monit stop director
monit stop director_scheduler

if $REGISTRY_EXISTS ; then
  monit stop registry
fi

for i in $(seq 60)
do
    sleep 10

    if [ -z "$(monit summary | grep '^Process.*director.*not monitored$')" ];then
        continue
    fi

    if [ -z "$(monit summary | grep '^Process.*director_scheduler.*not monitored$')" ];then
        continue
    fi

    if $REGISTRY_EXISTS ; then
        if [ -z "$(monit summary | grep '^Process.*registry.*not monitored$')" ];then
            continue
        fi
    fi

    break
done

if [ "$adapter" = 'postgres' ];then
    export PGPASSWORD=$pass

    psql -U$db_su -h$host $db_name -c"drop schema public cascade; create schema public;"
    psql -U$db_su -h$host $db_name -c"grant all on schema public to $db_su; grant all on schema public to public;"
    tar -xzvf $backup_file -O | psql -U$user -h$host $db_name

elif [ "$adapter" = 'mysql2' ];then
    export MYSQL_PWD=$pass
    monit restart mysql

    for i in $(seq 60)
    do
        sleep 10
        if [ -n '$(monit summary | grep "^Process.*mysql.*running$")' ];then
            break
        fi
    done

    mysql -u$user -h$host -e "drop database $db_name"
    mysql -u$user -h$host -e "create database $db_name"
    tar -xzvf $backup_file -O | mysql -u$user -h$host $db_name
fi

monit start director
monit start director_scheduler

if $REGISTRY_EXISTS ; then
  monit start registry
fi
