#!/bin/bash

RUN_DIR=/var/vcap/sys/run/registry
LOG_DIR=/var/vcap/sys/log/registry
PIDFILE=$RUN_DIR/registry.pid
RUNAS=vcap

export PATH=/var/vcap/packages/ruby/bin:$PATH
export BUNDLE_GEMFILE=/var/vcap/packages/registry/Gemfile
export GEM_HOME=/var/vcap/packages/registry/gem_home/ruby/2.1.0

function pid_exists() {
  ps -p $1 &> /dev/null
}

case $1 in

  start)
    mkdir -p $RUN_DIR $LOG_DIR
    chown -R $RUNAS:$RUNAS $RUN_DIR $LOG_DIR

    echo $$ > $PIDFILE

    chpst -u $RUNAS:$RUNAS \
      /var/vcap/packages/registry/bin/bosh-registry-migrate \
      -c /var/vcap/jobs/registry/config/registry.yml \
      >>$LOG_DIR/migrate.stdout.log 2>>$LOG_DIR/migrate.stderr.log

    if [ $? -ne 0 ]; then
      echo "migration failed"
      exit 1
    fi

    exec chpst -u $RUNAS:$RUNAS \
      /var/vcap/packages/registry/bin/bosh-registry \
      -c /var/vcap/jobs/registry/config/registry.yml \
      >>$LOG_DIR/registry.stdout.log 2>>$LOG_DIR/registry.stderr.log
    ;;

  stop)
    PID=$(head -1 $PIDFILE)
    if [ ! -z $PID ] && pid_exists $PID; then
      kill $PID
    fi
    while [ -e /proc/$PID ]; do sleep 0.1; done
    rm -f $PIDFILE
    ;;

  *)
  echo "Usage: registry_ctl {start|stop}" ;;
esac
exit 0
