---
aws:
  access_key_id: ...
  secret_access_key: ...
  region: us-east-1
name: dev102
vpc:
  domain: dev102.cf.com
  instance_tenancy: default
  cidr: 10.10.0.0/16
  subnets:
    bosh1:
      cidr: 10.10.0.0/24
      availability_zone: us-east-1a
      default_route: igw
      nat_instance:
        name: cf_nat_box
        ip: 10.10.0.10  # spin up NAT instance at fixed IP of 10.10.0.10
        security_group: open
        key_name: bosh
    cf1:
      cidr: 10.10.1.0/24
      availability_zone: us-east-1a
      default_route: cf_nat_box
    cf2:
      cidr: 10.10.2.0/24
      availability_zone: us-east-1b
  dhcp_options:
    domain_name: dev102.cf.com
    domain_name_servers:
      - 10.10.0.6
      - 172.16.0.23
  security_groups:
    - name: open
      ingress:
        - protocol: tcp
          ports: 0 - 65535
          sources: 0.0.0.0/0
        - protocol: udp
          ports: 0 - 65535
          sources: 0.0.0.0/0
    - name: ssh
      ingress:
        - protocol: tcp
          ports: 22
          sources: 0.0.0.0/0
  elbs:
    external-elb-1:
      domain: dev102.cf.com
      dns_record: "*"
      ttl: 60
      subnets:
      - bosh
      security_group: open
      https: true
      ssl_cert: my_cert_1
ssl_certs:
  my_cert_1:
    private_key: /path/to/private_key
    certificate: /path/to/certificate
    certificate_chain: /path/to/certificate_chain
elastic_ips:
  micro:
    instances: 1
    dns_record: micro
    ttl: 60
  bosh:
    instances: 1
    dns_record: bosh
  bat:
    instances: 1
    dns_record: bat
key_pairs:
  dev102: /tmp/somekey
rds:
  - instance: ccdb
    tag: cc
    subnets:
      - cf_rds1
      - cf_rds2
  - instance: uaadb
    tag: uaa
    subnets:
      - cf_rds1
      - cf_rds2
  - instance: bosh
    tag: bosh
    subnets:
      - bosh_rds1
      - bosh_rds2
s3:
  - bucket_name: b1
    tag: blobstore
  - bucket_name: b2
    tag: other
