#!/bin/sh

echo "Micro Cloud Foundry component licenses are available in:"
echo "  /var/vcap/micro/LICENSES"
echo "Micro Cloud Foundry Software Beta Test Agreement is available in:"
echo "  /var/vcap/micro/SBTA"
echo ""
