---
name: Test Director
port: 8081

logging:
  level: ERROR

redis:
  host: 127.0.0.1
  port: 63790
  password:

dir: /tmp/boshdir
db:
  database: "sqlite:///:memory:"
  max_connections: 32
  pool_timeout: 10
blobstore:
  plugin: simple
  properties:
    endpoint: http://127.0.0.1
    user: admin
    password:

cloud:
  plugin: dummy
  # to be added
