source :rubygems

gemspec

gem "rake"

group :development, :test do
  gem "ci_reporter"
  gem "rspec", "~>2.10"
  gem "nokogiri-diff", "~>0.1.2"

  gem "rcov", :platforms => :ruby_18
  gem "simplecov", :platforms => :ruby_19
  gem "simplecov-rcov", :platforms => :ruby_19
end
