AllCops:
  Includes:
    - Gemfile
    - Rakefile
  Excludes:
   - bin/**
   - bosh_agent/**
   - bosh_aws_cpi/**
   - bosh_cli/**
   - bosh_cli_plugin_aws/**
   - bosh_cli_plugin_micro/**
   - bosh_common/**
   - bosh_cpi/**
   - bosh_encryption/**
   - bosh_openstack_cpi/**
   - bosh_registry/**
   - bosh_vsphere_cpi/**
   - director/**
   - health_monitor/**
   - monit_api/**
   - package_compiler/**
   - release/**
   - ruby_vim_sdk/**
   - simple_blobstore_server/**
   - spec/**
   - stemcell_builder/**
   - vendor/**
   - tmp/**

Encoding:
  Enabled: false

LineLength:
  Max: 119

Documentation:
  Enabled: false

CaseIndentation:
  Enabled: false

DotPosition:
  Enabled: false
