AllCops:
  Include:
    - "**/Gemfile"
    - Rakefile
  Exclude:
    - agent_client/docs/**/*
    - bin/**/*
    - bosh_aws_cpi/**/*
    - bosh_cli/**/*
    - bosh_cli_plugin_aws/**/*
    - bosh_common/**/*
    - bosh_cpi/**/*
    - bosh_openstack_cpi/**/*
    - bosh-registry/**/*
    - bosh_vsphere_cpi/**/*
    - bosh-monitor/**/*
    - bosh-release/**/*
    - bosh-stemcell/spec/stemcells/centos_6.5_spec.rb
    - bosh-stemcell/spec/stemcells/centos_7_spec.rb
    - release/**/*
    - simple_blobstore_server/**/*
    - spec/**/*
    - stemcell_builder/**/*
    - vendor/**/*
    - tmp/**/*
    - go/**/*

CollectionMethods:
  Enabled: false # Enabling this doesn't like "inject"

Encoding:
  Enabled: false

LineLength:
  Max: 119

Documentation:
  Enabled: false

CaseIndentation:
  Enabled: false

DotPosition:
  Enabled: false

MethodLength:
  CountComments: false
  Max: 20

Blocks:
  Enabled: false # {} for multi-line blocks in RSpec expectations is very common

TrivialAccessors:
  Enabled: false # Bosh::Stemcell::Infrastructure#light? was a false positive

SpecialGlobalVars:
  Enabled: false # Unfortunately $CHILD_STATUS isn't always the same as $?

AlignParameters:
  Enabled: false

IfUnlessModifier:
  Enabled: false # It's nice to be able to use an if on its line

TrailingComma:
  Enabled: false

inherit_from: .rubocop_todo.yml
