AllCops:
  Includes:
    - Gemfile
    - Rakefile
  Excludes:
    - bin/**
    - bosh_agent/**
    - bosh_aws_cpi/**
    - bosh_cli/**
    - bosh_cli_plugin_aws/**
    - bosh_common/**
    - bosh_cpi/**
    - bosh_openstack_cpi/**
    - bosh-registry/**
    - bosh_vsphere_cpi/**
    - bosh_warden_cpi/**
    - bosh-monitor/**
    - bosh-release/**
    - bosh-stemcell/spec/stemcells/centos_spec.rb
    - release/**
    - simple_blobstore_server/**
    - spec/**
    - stemcell_builder/**
    - vendor/**
    - tmp/**

CollectionMethods:
  Enabled: false # Enabling this doesn't like "inject"

Encoding:
  Enabled: false

LineLength:
  Max: 119

Documentation:
  Enabled: false

CaseIndentation:
  Enabled: false

DotPosition:
  Enabled: false

MethodLength:
  CountComments: false
  Max: 20

Blocks:
  Enabled: false # {} for multi-line blocks in RSpec expectations is very common

TrivialAccessors:
  Enabled: false # Bosh::Stemcell::Infrastructure#light? was a false positive

AvoidPerlisms:
  Enabled: false # Unfortunately $CHILD_STATUS isn't always the same as $?

AlignParameters:
  Enabled: false

IfUnlessModifier:
  Enabled: false # It's nice to be able to use an if on its line
