require "rubygems"
require "bundler"
Bundler::GemHelper.install_tasks

desc "Run specs"
task :spec => [ "bundler:install:test", "test:spec" ]

desc "Run specs for CI"
task "spec:ci" => ["bundler:install:test", "test:spec:ci"]

desc "Run specs w/coverage"
task "spec:rcov" => ["bundler:install:test", "test:spec:rcov"]

environments = %w(test development production)

namespace "bundler" do

  desc "Install gems"
  task "install" do
    sh("bundle install")
  end

  environments = %w(test development production)

  environments.each do |env|
    desc "Install gems for #{env}"
    task "install:#{env}" do
      sh("bundle install --local --without #{(environments - [env]).join(' ')}")
    end
  end

end

namespace "test" do
  ["spec", "spec:rcov", "spec:ci" ].each do |task_name|
    task task_name do
      sh("cd spec && rake #{task_name}")
    end
  end
end
