---
http:
  port: 25930
  user: admin
  password: admin

logfile: /tmp/bosh-hm-functional-test

mbus:
  endpoint: nats://127.0.0.1:4222
  user:
  password:

director: &director
  endpoint: http://127.0.0.1:25555
  user:
  password:

intervals:
  poll_director: 60
  poll_grace_period: 30
  log_stats: 60
  analyze_agents: 60
  agent_timeout: 60
  rogue_agent_alert: 120
  prune_events: 30

plugins:
  - name: dummy
    events:
      - alert
      - heartbeat