---
http:
  port: 25930
  user: admin
  password: admin

mbus:
  endpoint: nats://127.0.0.1:4222
  user:
  password:

director:
  endpoint: http://127.0.0.1:25555
  user:
  password:

intervals:
  poll_director: 60
  poll_grace_period: 30
  log_stats: 60
  analyze_agents: 60
  agent_timeout: 60
  rogue_agent_alert: 120
  prune_events: 30

plugins:

  - name: logger

  - name: nats
    events:
      - alert
      - heartbeat
    options:
      endpoint: nats://127.0.0.1:4222
      user:
      password:

  - name: email
    events:
      - alert
    options:
      recipients:
        - user@example.com
      smtp:
        from: bosh.alerts@example.com
        host: smtp.example.com
        port: 25
        auth: plain
        user: user
        password: pass
        tls: true
        domain: example.com

  - name: tsdb
    events:
      - alert
      - heartbeat
    options:
      host: localhost
      port: 4242

  - name: varz
    events:
      - alert
      - heartbeat
