---
mbus:
  endpoint: nats://127.0.0.1:4222
  user:
  password:

director:
  endpoint: http://127.0.0.1:25555
  user:
  password:

intervals:
  poll_director: 60
  log_stats: 60
  agent_timeout: 10

alerts:
  plugin: email
  options:
    recipients:
      - olegs@vmware.com
    smtp:
      from: bosh.alerts@gmail.com
      host: smtp.gmail.com
      port: 587
      user: bosh.alerts
      password: dragonagezb
      auth: plain
      domain: gmail.com

