---
mbus:
  endpoint: nats://127.0.0.1:4222
  user:
  password:

director:
  endpoint: http://127.0.0.1:25555
  user:
  password:

intervals:
  poll_director: 60
  poll_grace_period: 30
  log_stats: 60
  agent_timeout: 60
  analyze_agents: 60
  agent_timeout: 60

alert_delivery_agents:

  - plugin: logger

  - plugin: email
    recipients:
      - olegs@vmware.com
    smtp:
      from: bosh.alerts@gmail.com
      host: smtp.gmail.com
      port: 587
      auth: plain
      user: bosh.alerts
      password: dragonagezb
      tls: true
      domain: gmail.com

