#!/bin/bash

# BPM will execute this script after monit starts it,
# but before it lays down PID file.

set -e

source /var/vcap/jobs/director/env

/var/vcap/packages/director/bin/bosh-director-migrate \
  -c /var/vcap/jobs/director/config/director.yml
