#!/bin/bash

set -e

source /var/vcap/jobs/director/env

/var/vcap/packages/director/bin/bosh-director-migrate \
  -c /var/vcap/jobs/director/config/director.yml

exec /var/vcap/packages/director/bin/bosh-director \
  -c /var/vcap/jobs/director/config/director.yml
