#!/bin/bash

source /var/vcap/jobs/director/env

RUN_DIR=/var/vcap/sys/run/director
LOG_DIR=/var/vcap/sys/log/director
mkdir -p $LOG_DIR

default_wait_time=15

stop_workers() {
  for pid_file in /var/vcap/sys/run/bpm/director/worker_*.pid; do
    if [ -f "$pid_file" ] ; then
      worker_pid=`cat ${pid_file}`
      # Stop DJ workers from accepting any new jobs
      kill -s USR1 ${worker_pid}
    fi
  done
}

stop_workers

num_workers=`/var/vcap/packages/director/bin/bosh-director-drain-workers -r -c /var/vcap/jobs/director/config/director.yml 2>>$LOG_DIR/drain.stderr.log`

if ([ $? != 0 ] || [ $num_workers -eq 0 ]); then
  echo 0
else
  echo -$default_wait_time
fi
