#!/bin/bash

RUN_DIR=/var/vcap/sys/run/director
LOG_DIR=/var/vcap/sys/log/director
JOB_DIR=/var/vcap/jobs/director
PIDFILE=$RUN_DIR/nginx.pid
SSL_DIR=/var/vcap/jobs/director/config/ssl
TMP_DIR=/var/vcap/data/director/tmp
RUNAS=vcap

function pid_exists() {
  ps -p $1 &> /dev/null
}

case $1 in

  start)
    mkdir -p $RUN_DIR $LOG_DIR $TMP_DIR

    echo $$ > $PIDFILE

    chown -R $RUNAS:$RUNAS $RUN_DIR $LOG_DIR $TMP_DIR

    # workaround. nginx upload module ignores the proxy_temp_path directive
    ln -fs $TMP_DIR/proxy /var/vcap/packages/nginx/proxy_temp

    exec chpst -u $RUNAS:$RUNAS /var/vcap/packages/nginx/sbin/nginx -c $JOB_DIR/config/nginx.conf \
      >>$LOG_DIR/nginx.stdout.log 2>>$LOG_DIR/nginx.stderr.log
    ;;

  stop)
    PID=$(head -1 $PIDFILE)
    if [ ! -z $PID ] && pid_exists $PID; then
      kill $PID
    fi
    TRIES=0
    while [ -e /proc/$PID ]
    do
      TRIES=$(( $TRIES + 1 ))
      if [ $TRIES -gt 100 ]; then
        CHILD_PIDS=$(ps --forest -o pid=  -g $(ps -o sid= $PID) | sed 's/ //g' | grep -v "^${PID}$")
        kill -9 $PID
        for CHILD_PID in $CHILD_PIDS; do
          kill -9 $CHILD_PID
        done
      fi
      sleep 0.1
    done
    rm -f $PIDFILE
    ;;

  *)
    echo "Usage: nginx_ctl {start|stop}" ;;
esac
exit 0
