---
name: test
releases:
- name: simple
  version: 2
resource_pools:
- name: rp
  stemcell:
    name: ubuntu
    version: 1
networks:
- name: default
jobs:
- name: job1
  template: xyz
  networks:
  - name: default
- name: old_job
  template: xyz
  networks:
  - name: default
