require "rubygems"
require "rake"
require "bundler"

require "rspec/core/rake_task"

APP_DIR = File.expand_path(File.join("..", ".."), __FILE__)
ENV["BUNDLE_GEMFILE"] ||= File.join(APP_DIR, "Gemfile")

Bundler.setup(:default, :test)

desc "Run all examples"
RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern    = "**/*_spec.rb"      
  t.rspec_opts = %w[--color]
end

task :default => [:spec, :cucumber]


