#!/bin/bash

RUN_DIR=/var/vcap/sys/run/blobstore
LOG_DIR=/var/vcap/sys/log/blobstore
DATA=/var/vcap/store/blobstore
TMPDIR=$DATA/tmp
export TMPDIR

PIDFILE=$RUN_DIR/blobstore.pid

PATH=/var/vcap/packages/ruby/bin:$PATH
export PATH

case $1 in

  start)
    mkdir -p $RUN_DIR $LOG_DIR $TMPDIR
	chown -R vcap $RUN_DIR $LOG_DIR $DATA

    echo $$ > $PIDFILE

    exec chpst -u vcap /var/vcap/packages/blobstore/bosh/simple_blobstore_server/bin/simple_blobstore_server -c /var/vcap/jobs/blobstore/config/blobstore.yml >>$LOG_DIR/blobstore.stdout.log 2>>$LOG_DIR/blobstore.stderr.log
    ;;

  stop)
    PID=$(head -1 $PIDFILE)
    kill $PID
    while [ -e /proc/$PID ]; do sleep 0.1; done
    rm -f $PIDFILE
    ;;

  *)
  echo "Usage: blobstore_ctl {start|stop}" ;;
esac
exit 0
