#!/bin/bash

RUN_DIR=/var/vcap/sys/run/blobstore
LOG_DIR=/var/vcap/sys/log/blobstore
PIDFILE=$RUN_DIR/nginx.pid

DATA=/var/vcap/store/blobstore
TMP_DIR=$DATA/tmp/uploads

function pid_exists() {
  ps -p $1 &> /dev/null
}

case $1 in

  start)
    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR
    mkdir -p $TMP_DIR
  	chown -R vcap:vcap $RUN_DIR $LOG_DIR $DATA

    echo $$ > $PIDFILE

    exec /var/vcap/packages/nginx/sbin/nginx -c /var/vcap/jobs/blobstore/config/nginx.conf >>$LOG_DIR/nginx.stdout.log 2>>$LOG_DIR/nginx.stderr.log
    ;;

  stop)
    PID=$(head -1 $PIDFILE)
    if [ ! -z $PID ] && pid_exists $PID; then
      kill $PID
    fi
    while [ -e /proc/$PID ]; do sleep 0.1; done
    rm -f $PIDFILE
    ;;

  *)
  echo "Usage: nginx_ctl {start|stop}" ;;
esac
exit 0
