---
name: Local Director
port: 25555
logging:
  level: DEBUG
redis:
  host: 127.0.0.1
  password:
dir: /tmp/boshdir
db:
  database: "sqlite:///bosh/director/director.db"
  max_connections: 32
  pool_timeout: 10
blobstore:
  provider: simple
  options:
    endpoint: http://127.0.0.1:9999
    user: admin
    password: admin
cloud:
  plugin: warden
  properties:
    warden:
      unix_domain_socket: "/tmp/warden.sock"
    agent:
      ntp: []
      blobstore:
        provider: simple
        options:
          endpoint: http://10.0.2.15:9999
          user: admin
          password: admin
      mbus: "nats://nats:nats@10.0.2.15:4222"
    stemcell:
      root: "/var/vcap/stemcell"
    disk:
      root: "/var/vcap/disk"
      fs: "ext4"
      pool_size: 128
      pool_start_number: 10
      device_path_prefix: "/dev/sdz"
