source :rubygems
gemspec

gem "rake"

#group :development do
#  gem "ruby-debug", :platforms => :ruby_18
#  gem "ruby-debug19", :platforms => :ruby_19
#end

group :development, :test do
  gem "sqlite3"
  gem "sys-filesystem"
  gem "bosh_cpi"
  gem "bosh_common"

  gem "ci_reporter"
  gem "rspec", "~>2.10"

  gem "rcov", :platforms => :ruby_18
  gem "simplecov", :platforms => :ruby_19
  gem "simplecov-rcov", :platforms => :ruby_19
end

gem "warden-client", :git => "https://github.com/cloudfoundry/warden.git", :ref => 'be42aec7'
