#!/bin/bash

PIDFILE=/var/vcap/sys/run/goobaz.pid

case $1 in

  start)
    echo $$ > $PIDFILE
    exec /bin/sh /var/vcap/packages/baz/run.sh
    ;;

  stop)
    tail -1 $PIDFILE | xargs kill
    rm -rf $PIDFILE
    ;;

  *)
  echo "Usage: goobaz_ctl {start|stop}" ;;
esac
exit 0
