---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu

inputs:
  - name: bosh-src
  - name: bosh-deployment
  - name: bosh-cli

run:
  path: bosh-src/ci/tasks/prepare-container-bosh-docker-build-context.sh

outputs:
  - name: docker-build-context

params:
  container_engine: ~ # docker|garden
