VAGRANTFILE_API_VERSION = '2'
IMAGE_TAG = 'bosh-container'
DOCKER_REGISTRY = 'docker.gocd.cf-app.com:5000'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # trusty (latest), virtualbox only
  config.vm.box = 'ubuntu/trusty64'

  config.vm.provider(:virtualbox) do |v|
    v.name = 'bosh-docker-builder'
    v.customize ['modifyvm', :id, '--cpus', '4']
    v.customize ['modifyvm', :id, '--memory', '4096']
  end

  # mount bosh dir for testing
  # config.vm.synced_folder '../../', '/opt/bosh'

  config.vm.provision('docker')
  config.vm.provision('shell') do |s|
    s.inline = "docker build -t #{DOCKER_REGISTRY}/#{IMAGE_TAG} /vagrant && " +
               "docker push #{DOCKER_REGISTRY}/#{IMAGE_TAG}"
  end
end
