VAGRANTFILE_API_VERSION = '2'
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  IMAGE_TAG = 'bosh-container'
  DOCKER_REGISTRY = 'docker.gocd.cf-app.com:5000'
  # trusty 14.04 w/ docker & networking fix, virtualbox only
  #config.vm.box = '3scale/docker'
  # trusty 14.04.1, virtualbox only
  config.vm.box = 'ubuntu/trusty64'

  config.vm.provider(:virtualbox) do |v|
    v.name = 'bosh-docker-builder'
  end

  config.vm.provision('docker') do |d|
    #d.pull_images "ubuntu"
    d.build_image('/vagrant', args: "-t #{DOCKER_REGISTRY}/#{IMAGE_TAG}")
  end

  config.vm.provision('shell') do |s|
    s.inline = "docker push #{DOCKER_REGISTRY}/#{IMAGE_TAG}"
  end
end
