require "tempfile"
require "rake"

APP_DIR = File.expand_path(File.join("..", ".."), __FILE__)
ENV["BUNDLE_GEMFILE"] ||= File.join(APP_DIR, "Gemfile")
require "rubygems"
require "bundler"
Bundler.setup(:default, :test)

require "rspec/core/rake_task"
require "ci/reporter/rake/rspec"

desc "Run all examples"
RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern    = "**/*_spec.rb"
  t.rspec_opts = %w[--color]
end

task :default => [:spec]

reports_dir = File.expand_path(File.join(File.dirname(__FILE__), "..", "spec_reports"))

ENV["CI_REPORTS"] = reports_dir

namespace "spec" do
  gemfile   = "../Gemfile"
  spec_opts = ["--format", "documentation", "--colour"]

  desc "Run specs for ci"
  task "ci" => [ "ci:setup:rspec", "spec:rcov" ]

  desc "Run spec with coverage"
  task :rcov => :cleanup_coverage do
    require "simplecov"
    require "simplecov-rcov"
    require "simplecov-clover"

    class SimpleCov::Formatter::CombinedFormatter
      def format(result)
        SimpleCov::Formatter::CloverFormatter.new.format(result)
        SimpleCov::Formatter::RcovFormatter.new.format(result)
      end
    end

    SimpleCov.formatter = SimpleCov::Formatter::CombinedFormatter
    SimpleCov.root('..')
    SimpleCov.coverage_dir('cov')
    SimpleCov.start do
      require "rspec/core"
      add_filter "/spec/"
      spec_dir = File.expand_path("..", __FILE__)
      RSpec::Core::Runner.disable_autorun!
      RSpec::Core::Runner.run([spec_dir], STDERR, STDOUT)
    end
  end

  task "cleanup_coverage" do
    rm_rf "cov"
  end

end
