source :rubygems

gem "rake"
gem "sinatra"
gem "thin"
gem "haml"
gem "json"
gem "rest-client"

group :test do
  gem "rack-test"
  gem "rcov"
  gem "rcov_analyzer"
  gem "rspec"
  gem "ruby-debug"
end
