task :bundle_install do
  sh("bundle --local install")
end

task :start => :bundle_install do
  sh("./bin/dashboard")
end

task :production => :bundle_install do
  sh("env RACK_ENV=production ./bin/dashboard")
end
