#!/bin/bash

RUN_DIR=/var/vcap/sys/run/health_monitor
LOG_DIR=/var/vcap/sys/log/health_monitor
PIDFILE=$RUN_DIR/health_monitor.pid
RUNAS=vcap

export PATH=/var/vcap/packages/ruby/bin:$PATH

case $1 in

  start)
    mkdir -p $RUN_DIR $LOG_DIR
    chown -R $RUNAS:$RUNAS $RUN_DIR $LOG_DIR

    echo $$ > $PIDFILE

    exec chpst -u $RUNAS:$RUNAS \
      /var/vcap/packages/health_monitor/bosh/health_monitor/bin/health_monitor \
      -c /var/vcap/jobs/health_monitor/config/health_monitor.yml \
      >>$LOG_DIR/health_monitor.stdout.log 2>>$LOG_DIR/health_monitor.stderr.log
    ;;

  stop)
    PID=$(head -1 $PIDFILE)
    kill $PID
    while [ -e /proc/$PID ]; do sleep 0.1; done
    rm -f $PIDFILE
    ;;

  *)
  echo "Usage: health_monitor_ctl {start|stop}" ;;
esac
exit 0
