VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # trusty (latest), virtualbox only
  config.vm.box = 'ubuntu/trusty64'

  config.vm.provider(:virtualbox) do |v|
    v.name = 'bosh-docker-builder'
    v.customize ['modifyvm', :id, '--cpus', '4']
    v.customize ['modifyvm', :id, '--memory', '4096']
  end

  # mount bosh dir for testing
  config.vm.synced_folder('../../', '/opt/bosh', owner: 'root', group: 'root')

  if Vagrant.has_plugin?("vagrant-proxyconf")
    if ENV["http_proxy"]
      config.proxy.http        = ENV["http_proxy"]
      config.apt_proxy.http    = ENV["http_proxy"]
    end
    if ENV["https_proxy"]
      config.proxy.https        = ENV["https_proxy"]
      config.apt_proxy.https    = ENV["https_proxy"]
    end
    if ENV["no_proxy"]
      config.proxy.no_proxy     = ENV["no_proxy"]
    end
  end

  config.vm.provision('docker')
end
