source :rubygems

gem "highline"
gem "json_pure"
gem "progressbar"
gem "rest-client", ">= 1.6.3"
gem "terminal-table"
gem "rake"
gem "blobstore_client", "~> 0.2" # 0.2 has streaming support

group :test do
  gem "ci_reporter"
  gem "rcov"
  gem "rcov_analyzer"
  gem "rspec"
  gem "ruby-debug", :platforms => :ruby_18
  gem "ruby-debug19", :platforms => :ruby_19
  gem "simplecov", :platform => :ruby_19
end
