---
name: test-director
port: 25555
logging:
  level: DEBUG
  file: /var/vcap/deploy/bosh/director/shared/logs/director.debug.log
redis:
  host: 10.147.0.0
  port: 25255
  password: R3d!S
mbus: nats://bosh:b0$H@10.147.0.0:4222
dir: /var/vcap/deploy/bosh/director/shared/system
max_tasks: 10
db:
  database: postgres://bosh:b0$H@10.147.0.0/bosh
  max_connections: 32
  pool_timeout: 10
blobstore:
  plugin: simple
  properties:
    endpoint: http://10.147.0.0:25250
    user: director
    password: d!r3ct0r
cloud:
  plugin: vcd
  properties:
    agent:
      ntp:
       - ntp01.las01.emcatmos.com
      blobstore:
        plugin: simple
        properties:
          endpoint: http://10.147.0.0:25250
          user: agent
          password: Ag3Nt
      mbus: nats://bosh:b0$H@10.147.0.0:4222
    vcds:
      - url: https://10.147.0.0:8443
        user: cfadmin
        password: akimbi
        entities:
          organization: cf-org
          virtual_datacenter: cf-vdc
          vapp_catalog: cf-catalog
          media_catalog: cf-catalog
          vm_metadata_key: cf-agent-env
          description: vcd-cf
        control:
          retries:
            default: 5
            upload_vapp_files: 7
            cpi: 1
          delay: 1
          time_limit_sec:
            default: 120
            delete_vapp_template: 120
            delete_vapp: 120
            delete_media: 120
            instantiate_vapp_template: 300
            power_on: 600
            power_off: 600
            undeploy: 720
            process_descriptor_vapp_template: 300
            http_request: 240
          backoff: 2
          rest_throttle:
            min: 0
            max: 1
        debug:
          delete_vapp: true
        testing:
          cookies: fake-cookie
    log_file: /tmp/vcd-cpi-test/debug
