# https://golangci-lint.run/usage/configuration/
run:
  timeout: 3m # 1m default times out on github-action runners

linters:
  enable:
  - goimports

output:
  # Sort results by: filepath, line and column.
  sort-results: true
