---
networks:

- name: default
  subnets:
- name: lb
  subnets:
  - static:
    - 172.28.3.145-172.28.3.146
    range: 172.28.3.144/28
    gateway: 172.31.116.1
    dns:
    - 172.30.22.153
    - 172.30.22.154
    cloud_properties:
      name: VLAN3057
