source 'https://rubygems.org'

gem 'bosh-core', path: '../bosh-core'
gem 'bosh-director-core', path: '../bosh-director-core'
gem 'bosh-registry', path: '../bosh-registry'
gem 'bosh-stemcell', path: '../bosh-stemcell'
gem 'bosh_aws_cpi', path: '../bosh_aws_cpi'
gem 'bosh_cli', path: '../bosh_cli'
gem 'bosh_cpi', path: '../bosh_cpi'
gem 'bosh_openstack_cpi', path: '../bosh_openstack_cpi'
gem 'bosh_vsphere_cpi', path: '../bosh_vsphere_cpi'
gem 'fakefs', git: 'https://github.com/pivotal-cf-experimental/fakefs.git', ref: 'ebde3d6c'


gemspec
