---
packages:
- name: mysql
  version: !binary |-
    ZTUzMDlhZWQ4OGY1Y2M2NjJiYzc3OTg4YTMxODc0NDYxZjdjNGZiOA==
  sha1: !binary |-
    Y2MyY2I5MjZiNmE2NDRkMjY5MjcwMGM1YWUzYmQ0ZjViODRkY2I4Mg==
  fingerprint: !binary |-
    ZTUzMDlhZWQ4OGY1Y2M2NjJiYzc3OTg4YTMxODc0NDYxZjdjNGZiOA==
  dependencies: []
- name: nginx
  version: fd1339e8f0ffe194e1c63b8651d7192a4468dbc5
  sha1: !binary |-
    MmQ0ODQ2ZTkzZmZkYmJhYjE0MGMxNWNjYjNkZGY0ODQ4Zjg0ZmNiZA==
  fingerprint: !binary |-
    ZmQxMzM5ZThmMGZmZTE5NGUxYzYzYjg2NTFkNzE5MmE0NDY4ZGJjNQ==
  dependencies: []
- name: postgres
  version: !binary |-
    YWE3ZjViMTEwZThiMzY4ZWViOGY1ZGQwMzJlMWNhYjY2ZDg2MTRjZQ==
  sha1: !binary |-
    YTg1ZjJhMWVmYTdkZmYzNGFiNzcyZDY3MTkxZDIzMzYzOTU5Mjc2YQ==
  fingerprint: !binary |-
    YWE3ZjViMTEwZThiMzY4ZWViOGY1ZGQwMzJlMWNhYjY2ZDg2MTRjZQ==
  dependencies: []
- name: nats
  version: 6a31c7bb0d5ffa2a9f43c7fd7193193438e20e92
  sha1: !binary |-
    ZGVlNzBmZWY2M2FhMzVhMGQ4ZTFkOGZlNzMwYjU1OTY5MDRjNGE1OQ==
  fingerprint: !binary |-
    NmEzMWM3YmIwZDVmZmEyYTlmNDNjN2ZkNzE5MzE5MzQzOGUyMGU5Mg==
  dependencies:
  - ruby
- name: blobstore
  version: !binary |-
    MzFhMGZjZmJlZWFhODljNTg2MTUyMjhhNzg0M2RmYmRmMWY3ZTM0ZA==
  sha1: !binary |-
    ZDRhYzI4NjU5ZTRiMTUxZTg5NzM5ODUwYmM2NGVlNWMyZmE0OTM1Ng==
  fingerprint: !binary |-
    MzFhMGZjZmJlZWFhODljNTg2MTUyMjhhNzg0M2RmYmRmMWY3ZTM0ZA==
  dependencies:
  - ruby
- name: health_monitor
  version: !binary |-
    NWI2YjFkMjBiM2RhNWZkMWRkYjE2NDdiODdlOWFjYzk3NTA0NGMyZg==
  sha1: !binary |-
    YTU4MTUwNGZkMmViMjkyMTEwNTVlMTMwZDNiOTNkMGM3OTNkMmFjOQ==
  fingerprint: !binary |-
    NWI2YjFkMjBiM2RhNWZkMWRkYjE2NDdiODdlOWFjYzk3NTA0NGMyZg==
  dependencies:
  - ruby
- name: common
  version: !binary |-
    MTMyNGQzMmRiZGE0MGRhODhhYWRlMWUwN2IyMjZhMjA4NjAyYmFmZg==
  sha1: !binary |-
    OTQwN2QxZDNkYTMwZGVkMWU5NTVhY2ZjODg5OTMwNGFhNThhMGU3OA==
  fingerprint: !binary |-
    MTMyNGQzMmRiZGE0MGRhODhhYWRlMWUwN2IyMjZhMjA4NjAyYmFmZg==
  dependencies: []
- name: genisoimage
  version: !binary |-
    MDA4ZDMzMmJhMTQ3MWJjY2Y5ZDlhZWI2NGMyNThmZGQ0YmY3NjIwMQ==
  sha1: !binary |-
    MmFjZjhkYTAyNTBkYjMxZTc2MmEyMzc1NmZkMGUxMmNmYTk0N2ViOQ==
  fingerprint: !binary |-
    MDA4ZDMzMmJhMTQ3MWJjY2Y5ZDlhZWI2NGMyNThmZGQ0YmY3NjIwMQ==
  dependencies: []
- name: registry
  version: !binary |-
    M2FlODBhMjczNTJlYWEzMDA5YzViNzgzZGEyNTM5OTUyMDdlYjI5MQ==
  sha1: !binary |-
    NGFmMzYxODBhYTAyZDVhNWUzY2YxNjU5MTUxMDk5ZjgyN2RkZWQ1Yw==
  fingerprint: !binary |-
    M2FlODBhMjczNTJlYWEzMDA5YzViNzgzZGEyNTM5OTUyMDdlYjI5MQ==
  dependencies:
  - libpq
  - mysql
  - ruby
- name: director
  version: !binary |-
    MjY1ODEzYjFlZTExZGNkMzI2MjQzN2I0ZTVhNWU3OWE0NDdlMjRjOA==
  sha1: !binary |-
    ZjNhMDZlMGU0OWZiODI2MzYxMDdkMjg5YWFjNzdiMjQ5M2ZiZGUyOQ==
  fingerprint: !binary |-
    MjY1ODEzYjFlZTExZGNkMzI2MjQzN2I0ZTVhNWU3OWE0NDdlMjRjOA==
  dependencies:
  - libpq
  - mysql
  - ruby
- name: libpq
  version: !binary |-
    NmFhMTlhZmIxNTNkYzI3NjkyNDY5M2RjNzI0NzYwNjY0Y2U2MTU5Mw==
  sha1: !binary |-
    N2YwZjQxODNkZWE5NjgzNzNmNzMwOTFkMWM5MTFkNWVkZWJjM2YyNQ==
  fingerprint: !binary |-
    NmFhMTlhZmIxNTNkYzI3NjkyNDY5M2RjNzI0NzYwNjY0Y2U2MTU5Mw==
  dependencies: []
- name: powerdns
  version: !binary |-
    ZTQxYmFmOGUyMzZiNWZlZDUyYmEzYzMzY2Y2NDZlNGIyZTBkNWE0ZQ==
  sha1: !binary |-
    NTdhNzZlNjVkYjA5MDAyYjFiOWEyNzdjMDQ4NzY3ZjUwZjQ4OGUzMQ==
  fingerprint: !binary |-
    ZTQxYmFmOGUyMzZiNWZlZDUyYmEzYzMzY2Y2NDZlNGIyZTBkNWE0ZQ==
  dependencies: []
- name: redis
  version: !binary |-
    ZWMyN2EwYjc4NDk4NjNiYzE2MGFjNTRjZTY2N2VjYWNkMDdmYzRjYg==
  sha1: !binary |-
    MzljYTA4OTY0MzQyNjcwMzc1NzVjNzU3ZTAxYmFkYjUwYjE1ZmQwYw==
  fingerprint: !binary |-
    ZWMyN2EwYjc4NDk4NjNiYzE2MGFjNTRjZTY2N2VjYWNkMDdmYzRjYg==
  dependencies: []
- name: ruby
  version: !binary |-
    ODFmZTgwMDk5MTMwZjA0ZGZmMmIwOGM4MGMwNGUwY2IzM2E5ZDNjYQ==
  sha1: !binary |-
    ZGU3MzRkNDZmZjE4NDI4YTgyNzhmZjZiYTc0NmEwYjIxMTZkYWU3NQ==
  fingerprint: !binary |-
    ODFmZTgwMDk5MTMwZjA0ZGZmMmIwOGM4MGMwNGUwY2IzM2E5ZDNjYQ==
  dependencies: []
jobs:
- name: postgres
  version: !binary |-
    NTFhNzM0Y2MzYWJiMDZhYjZkMmJhZjY4N2IyYjVlMzBkYzRkZDliNw==
  fingerprint: !binary |-
    NTFhNzM0Y2MzYWJiMDZhYjZkMmJhZjY4N2IyYjVlMzBkYzRkZDliNw==
  sha1: !binary |-
    MDQ1OTIxZjkzNGQ0YzFjMWFiYmE0MDJkMWMzZDU3MjAwYzM3ZTg4MQ==
- name: nats
  version: !binary |-
    YjYxOWZkZDM5ZjM0NGVlOWZiMWE3NjBkMGFkZTllYmY5ZGRjZWZlMg==
  fingerprint: !binary |-
    YjYxOWZkZDM5ZjM0NGVlOWZiMWE3NjBkMGFkZTllYmY5ZGRjZWZlMg==
  sha1: !binary |-
    ODAxZjU2OTQxOWYxNjA0MjhjMTQ3YjQzZjI4YjEwNzg5ZjkzNTY3ZA==
- name: blobstore
  version: ec529e2dceecbf1e39679a3a53bbdccfcac0fd44
  fingerprint: !binary |-
    ZWM1MjllMmRjZWVjYmYxZTM5Njc5YTNhNTNiYmRjY2ZjYWMwZmQ0NA==
  sha1: !binary |-
    OWJjNTM3YjdmZTk3MTMxMzExMTdiY2QyNGYyOTIxOWRmNmQ5MjJlNw==
- name: health_monitor
  version: 49d5d5d04d739178518d43692da320927284cfaa
  fingerprint: !binary |-
    NDlkNWQ1ZDA0ZDczOTE3ODUxOGQ0MzY5MmRhMzIwOTI3Mjg0Y2ZhYQ==
  sha1: !binary |-
    MDI3NTYzZDNjMTBlZGE3MDA4NDc0YWZlNGYwMTdmMGU4ZGVkZDE4Mg==
- name: registry
  version: 5b602791d9d6cf07f5dbd8b2a2ebc262f932a518
  fingerprint: !binary |-
    NWI2MDI3OTFkOWQ2Y2YwN2Y1ZGJkOGIyYTJlYmMyNjJmOTMyYTUxOA==
  sha1: !binary |-
    MjEyN2RkZWZkNmJjNGE2NGQ3MjdhZDJiZmM5Y2MxZTc1Mjc4MTE2NA==
- name: director
  version: fe06b07fd3f0e4794b8d0e83c9b670d25f7ee4e4
  fingerprint: !binary |-
    ZmUwNmIwN2ZkM2YwZTQ3OTRiOGQwZTgzYzliNjcwZDI1ZjdlZTRlNA==
  sha1: !binary |-
    NTkwZDk0ODQ0YTFmNWU2MWExNTBjMGE2NzMxNDJhZGFmOTE3MDA3Yw==
- name: powerdns
  version: !binary |-
    ZTUwODk4NmUxZDIyZWQzZDhmYzZhNWU5NjIwZDY3YTUxNWRhZjQ5NQ==
  fingerprint: !binary |-
    ZTUwODk4NmUxZDIyZWQzZDhmYzZhNWU5NjIwZDY3YTUxNWRhZjQ5NQ==
  sha1: !binary |-
    MDEyOTQ3ZWUyMTI3ZTVhYTg5MzRhYmJkMmI4YzUwMDgyOTZjOWZkNA==
- name: redis
  version: 8b447660541a0658b2cbed6f19932c769f037188
  fingerprint: !binary |-
    OGI0NDc2NjA1NDFhMDY1OGIyY2JlZDZmMTk5MzJjNzY5ZjAzNzE4OA==
  sha1: !binary |-
    ODczODEzNGU4YTMzNTJkYzE0MDgzODRiYjE4ODM1NzFmYTM2MzNmMw==
commit_hash: f58a035f
uncommitted_changes: true
name: bosh
version: '100.1'
