# Copyright (c) 2012 VMware, Inc.

require "rubygems"
require "bundler"
Bundler.setup(:default, :test)

require "rake"
require "rspec/core/rake_task"

desc "Run BAT tests"
task :bat => %w[bat:release bat:deployment bat:stemcell bat:log]

namespace "bat" do
  SPEC_OPTS = %w(--format documentation --color)

  desc "Verify BAT environment"
  RSpec::Core::RakeTask.new(:env) do |t|
    t.pattern = "spec/_init_spec.rb"
    t.rspec_opts = SPEC_OPTS
  end

  desc "Run release tests"
  RSpec::Core::RakeTask.new(:release => :env) do |t|
    t.pattern = "spec/release_spec.rb"
    t.rspec_opts = SPEC_OPTS
  end

  desc "Run deployment tests"
  RSpec::Core::RakeTask.new(:deployment => :env) do |t|
    t.pattern = "spec/deployment_spec.rb"
    t.rspec_opts = SPEC_OPTS
  end

  desc "Run stemcell tests"
  RSpec::Core::RakeTask.new(:stemcell => :env) do |t|
    t.pattern = "spec/deployment_spec.rb"
    t.rspec_opts = SPEC_OPTS
  end

  desc "Clean up lingering things on the director"
  RSpec::Core::RakeTask.new(:cleanup) do |t|
    t.pattern = "spec/cleanup_spec.rb"
    t.rspec_opts = SPEC_OPTS
  end

  desc "Run log tests"
  RSpec::Core::RakeTask.new(:log => :env) do |t|
    t.pattern = "spec/log_spec.rb"
    t.rspec_opts = SPEC_OPTS
  end

end