# Copyright (c) 2009-2012 VMware, Inc.

gem "rake"
gem "sequel"
gem "sinatra"
gem "thin"
gem "yajl-ruby"
gem "aws-sdk", ">=1.3.6"

group :production do
  gem "pg"
end

group :test, :development do
  gem "rack-test"

  gem "ci_reporter"
  gem "rspec"

  gem "ruby-debug", :platforms => :ruby_18
  gem "ruby-debug19", :platforms => :ruby_19

  gem "rcov", :platforms => :ruby_18

  gem "simplecov", :platforms => :ruby_19
  gem "simplecov-rcov", :platforms => :ruby_19

  gem "sqlite3"
end
