#!/bin/bash

RUN_DIR=/var/vcap/sys/run/blobstore
LOG_DIR=/var/vcap/sys/log/blobstore
STORE_DIR=/var/vcap/store/blobstore
TMP_DIR=/var/vcap/data/blobstore/tmp
JOB_DIR=/var/vcap/jobs/blobstore

PIDFILE=$RUN_DIR/nginx.pid
RUNAS=vcap

function pid_exists() {
  ps -p $1 &> /dev/null
}

source $JOB_DIR/helpers/utils.sh

case $1 in

  start)
    mkdir -p $RUN_DIR $LOG_DIR $STORE_DIR $TMP_DIR

    pid_guard $PIDFILE "nginx"

    echo $$ > $PIDFILE

    chown -R $RUNAS:$RUNAS $RUN_DIR $LOG_DIR $STORE_DIR $TMP_DIR

    exec chpst -u $RUNAS:$RUNAS /var/vcap/packages/nginx/sbin/nginx -c /var/vcap/jobs/blobstore/config/nginx.conf >>$LOG_DIR/nginx.stdout.log 2>>$LOG_DIR/nginx.stderr.log
    ;;

  stop)
    PID=$(head -1 $PIDFILE)
    if [ ! -z $PID ] && pid_exists $PID; then
      kill $PID
    fi
    while [ -e /proc/$PID ]; do sleep 0.1; done
    rm -f $PIDFILE
    ;;

  *)
  echo "Usage: nginx_ctl {start|stop}" ;;
esac
exit 0
