source :rubygems

group :development do
  gem "ruby-debug", :platforms => :ruby_18
  gem "ruby-debug19", :platforms => :ruby_19
end

gem "redis"
gem "nats"
gem "yajl-ruby", ">=1.1.0"
gem "SystemTimer", :platforms => :ruby_18
gem "rake"
gem "ci_reporter"
gem "rspec"
gem "rest-client"
