require "tempfile"
require "rake"

ENV["BUNDLE_GEMFILE"] ||= File.join(File.dirname(__FILE__), "..", "Gemfile")
require "rubygems"
require "bundler"
Bundler.setup(:default, :test)

require "rspec/core/rake_task"
require "ci/reporter/rake/rspec"

$:.unshift(File.expand_path("../../bosh/cli/bin"), __FILE__)

reports_dir = File.expand_path(File.join(File.dirname(__FILE__), "..", "spec_reports"))
ENV["CI_REPORTS"] = reports_dir

task "spec:ci" => [ "ci:setup:rspec", "spec" ]

RSpec::Core::RakeTask.new do |t|
  t.pattern    = "*_spec.rb"      
  t.rspec_opts = [ "--format", "documentation", "--colour" ]
end


