# Copyright (c) 2009-2012 VMware, Inc.

source :rubygems
gemspec

gem "rake"

group :production do
  gem "pg"
end

group :development do
  gem "ruby-debug", :platforms => :ruby_18
  gem "ruby-debug19", :platforms => :ruby_19
end

group :test, :development do
  gem "rack-test"

  gem "ci_reporter"
  gem "rspec", "~>2.10"

  gem "rcov", :platforms => :ruby_18

  gem "simplecov", :platforms => :ruby_19
  gem "simplecov-rcov", :platforms => :ruby_19

  gem "sqlite3"
end