require "rake"
require "tempfile"

ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../../Gemfile", __FILE__)
require "rubygems"
require "bundler"
Bundler.setup(:default, :test)

require "rspec/core/rake_task"
require "ci/reporter/rake/rspec"

coverage_dir = File.expand_path(File.join(File.dirname(__FILE__), "..", "spec_coverage"))
reports_dir = File.expand_path(File.join(File.dirname(__FILE__), "..", "spec_reports"))
dump_file = File.join(Dir.tmpdir, "bosh-director.rcov")
ignore_pattern = "spec,[.]bundle,[/]gems[/]"

ENV["CI_REPORTS"] = reports_dir

task "spec" => ["ci:setup:rspec"]

desc "Run specs using RCov"
task "spec:rcov" => ["ci:setup:rspec", "spec:rcov_internal", "convert_rcov_to_clover"]

RSpec::Core::RakeTask.new do |t|
  t.pattern = "**/*_spec.rb"
  t.rspec_opts = ["--format", "progress", "--colour"]
end

RSpec::Core::RakeTask.new("spec:rcov_internal") do |t|
  sh("rm -f #{dump_file}")
  t.pattern = "**/*_spec.rb"
  t.rspec_opts = ["--format", "progress", "--colour"]
  t.rcov = true
  t.rcov_opts = %W{--exclude osx\/objc,gems\/,spec\/,features\/ -o "#{coverage_dir}"}
end

task "convert_rcov_to_clover" do |t|
  analyzer = File.join(File.dirname(__FILE__), "..", "..", "..", "lib", "rcov_analyzer.rb")
  clover_output = File.join(coverage_dir, "clover.xml")
  sh("ruby #{analyzer} #{dump_file} #{ignore_pattern} > #{clover_output}")
  sh("rm -f #{dump_file}")
end
