site :opscode

cookbook 'apt'
cookbook 'ruby_build', github: 'fnichol/chef-ruby_build', tag: 'v0.7.2'
cookbook 'rbenv', github: 'fnichol/chef-rbenv', tag: 'v0.7.2'
cookbook 'stemcell_builder', path: '../cookbooks/stemcell_builder'