#!/bin/sh
#
# Copyright (c) 2009-2012 VMware, Inc.

BOSH=/var/vcap/bosh
NTP_SERVER_FILE=$BOSH/etc/ntpserver
if [ -f $NTP_SERVER_FILE ]; then
	NTP_SERVER=`cat $NTP_SERVER_FILE`
	# Use -u option to prevent returning packets from being blocked by firewall
	/usr/sbin/ntpdate -u $NTP_SERVER > $BOSH/log/ntpdate.out 2>&1
fi
