---
groups:
  - name: google-stemcell
    jobs:
      - build-google-kvm-ubuntu-trusty
      - build-google-kvm-centos-7

jobs:
  - name: build-google-kvm-ubuntu-trusty
    plan:
      - aggregate:
          - get: version
            trigger: true
          - get: bosh-src
          - get: bosh-release
          - get: os-image
            resource: ubuntu-trusty-os-image

      - task: create-stemcell
        file: bosh-src/ci/pipelines/stemcell/tasks/build.yml
        privileged: true
        params:
          IAAS:       google
          HYPERVISOR: kvm
          OS_NAME:    ubuntu
          OS_VERSION: trusty

      - aggregate:
        - put: google-kvm-ubuntu-trusty
          params:
            file: stemcell/bosh-stemcell-*-google-kvm-ubuntu-trusty-go_agent.tgz

        - put: google-kvm-ubuntu-trusty-sha1
          params:
            file: stemcell/bosh-stemcell-*-google-kvm-ubuntu-trusty-go_agent.tgz.sha1

  - name: build-google-kvm-centos-7
    plan:
      - aggregate:
          - get: version
            trigger: true
          - get: bosh-src
          - get: bosh-release
          - get: os-image
            resource: centos-7-os-image

      - task: create-stemcell
        file: bosh-src/ci/pipelines/stemcell/tasks/build.yml
        privileged: true
        params:
          IAAS:       google
          HYPERVISOR: kvm
          OS_NAME:    centos
          OS_VERSION: 7

      - aggregate:
        - put: google-kvm-centos-7
          params:
            file: stemcell/bosh-stemcell-*-google-kvm-centos-7-go_agent.tgz

        - put: google-kvm-centos-7-sha1
          params:
            file: stemcell/bosh-stemcell-*-google-kvm-centos-7-go_agent.tgz.sha1

resources:
  - name: bosh-src
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh.git
      # TODO: change this back to master once GCE PR has been promoted
      branch: develop

  - name: version
    type: semver
    source:
      driver: s3
      key: bosh-stemcell/version
      bucket: {{version_bucket}}
      access_key_id: {{version_aws_access_key}}
      secret_access_key: {{version_aws_secret_key}}

  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh

  # os-images

  - name: ubuntu-trusty-os-image
    type: s3
    source:
      bucket: {{os_image_bucket}}
      versioned_file: bosh-ubuntu-trusty-os-image.tgz
      access_key_id: {{os_image_aws_access_key}}
      secret_access_key: {{os_image_aws_secret_key}}

  - name: centos-7-os-image
    type: s3
    source:
      bucket: {{os_image_bucket}}
      versioned_file: bosh-centos-7-os-image.tgz
      access_key_id: {{os_image_aws_access_key}}
      secret_access_key: {{os_image_aws_secret_key}}

  # stemcells
  - name: google-kvm-ubuntu-trusty
    type: s3
    source:
      bucket: {{stemcell_bucket}}
      regexp: bosh-stemcell-(.+)-google-kvm-ubuntu-trusty-go_agent.tgz
      access_key_id: {{stemcell_aws_access_key}}
      secret_access_key: {{stemcell_aws_secret_key}}

  - name: google-kvm-ubuntu-trusty-sha1
    type: s3
    source:
      bucket: {{stemcell_bucket}}
      regexp: bosh-stemcell-(.+)-google-kvm-ubuntu-trusty-go_agent.tgz.sha1
      access_key_id: {{stemcell_aws_access_key}}
      secret_access_key: {{stemcell_aws_secret_key}}

  - name: google-kvm-centos-7
    type: s3
    source:
      bucket: {{stemcell_bucket}}
      regexp: bosh-stemcell-(.+)-google-kvm-centos-7-go_agent.tgz
      access_key_id: {{stemcell_aws_access_key}}
      secret_access_key: {{stemcell_aws_secret_key}}

  - name: google-kvm-centos-7-sha1
    type: s3
    source:
      bucket: {{stemcell_bucket}}
      regexp: bosh-stemcell-(.+)-google-kvm-centos-7-go_agent.tgz.sha1
      access_key_id: {{stemcell_aws_access_key}}
      secret_access_key: {{stemcell_aws_secret_key}}
