module VCloudCloud

  VM_NIC_LIMIT  = 10

  # control options
  RETRIES_DEFAULT = 5
  RETRIES_UPLOAD_VAPP_FILES = 7
  RETRIES_CPI = 3
  DELAY = 1
  TIMELIMIT_DEFAULT = 1200
  TIMELIMIT_DELETE_VAPP_TEMPLATE = 1200
  TIMELIMIT_DELETE_VAPP = 1200
  TIMELIMIT_DELETE_MEDIA = 1200
  TIMELIMIT_INSTANTIATE_VAPP_TEMPLATE = 3000
  TIMELIMIT_POWER_ON = 6000
  TIMELIMIT_POWER_OFF = 6000
  TIMELIMIT_UNDEPLOY = 7200
  TIMELIMIT_PROCESS_DESCRIPTOR_VAPP_TEMPLATE = 3000
  TIMELIMIT_HTTP_REQUEST = 240
  BACKOFF = 2
  REST_THROTTLE_MIN = 0
  REST_THROTTLE_MAX = 1

  # debug option
  DEBUG_DELETE_VAPP = true

end
