---
cloud:
  plugin: warden
  properties:
    warden:
      unix_domain_socket: /tmp/warden.sock
    agent:
      ntp: []
      blobstore:
        plugin: local
        properties:
          blobstore_path: /var/vcap/micro_bosh/data/cache
      mbus: nats://nats:nats@localhost:4222
    stemcell:
      root: /var/vcap/stemcell
    disk:
      root: /var/vcap/disk
      fs: ext4
