source :rubygems

gem "rake"
gem "crack"

group :test do
  gem "ci_reporter"
  gem "rcov"
  gem "rcov_analyzer"
  gem "rspec"
  gem "ruby-debug", :platform => :ruby_18
  gem "ruby-debug19", :platform => :ruby_19
end
