source :rubygems

gem "rake"
gem "httpclient"
gem "aws-s3"
gem "uuidtools"
gem "ruby-atmos"

group :test do
  gem "ci_reporter"
  gem "rcov", :platforms => :ruby_18
  gem "rcov_analyzer", ">= 0.2", :platforms => :ruby_18
  gem "rspec", "=2.3.0"
  gem "ruby-debug", :platforms => :ruby_18
  gem "ruby-debug19", :platforms => :ruby_19
  gem "simplecov", :platforms => :ruby_19
  gem "simplecov-clover", :platforms => :ruby_19
  gem "simplecov-rcov", :platforms => :ruby_19
end

