source :rubygems

gem "rake"
gem "httpclient"
gem "aws-s3"
gem "uuidtools"

group :test do
  gem "ci_reporter"
  gem "rcov"
  gem "rcov_analyzer"
  gem "rspec", "=2.3.0"
  gem "ruby-debug", :platforms => :ruby_18
  gem "ruby-debug19", :platforms => :ruby_19
  gem "simplecov", :platforms => :ruby_19
  gem "simplecov-rcov", :platforms => :ruby_19
end

