require "rubygems"
require "bundler"

desc "Run specs"
task "spec" => [ "bundler:install:test", "test:spec" ]

desc "Run specs for CI"
task "spec:ci" => ["bundler:install:test", "test:spec:ci"]

desc "Run specs w/coverage"
task "spec:rcov" => ["bundler:install:test", "test:spec:rcov"]

gem_helper = Bundler::GemHelper.new(Dir.pwd)

desc "Build Bosh CLI gem into the pkg directory"
task "build" do
  gem_helper.build_gem
end

desc "Build and install Bosh CLI into system gems"
task "install" do
  sh("bundle install --local --without test development")
  gem_helper.install_gem
end

namespace "bundler" do
  desc "Install gems"
  task "install" do
    sh("bundle install")
  end

  environments = %w(test development production)

  environments.each do |env|
    desc "Install gems for #{env}"
    task "install:#{env}" do
      Bundler.with_clean_env do
        if ENV.has_key? 'RUBYOPT'
          ENV['RUBYOPT'] = ENV['RUBYOPT'].sub '-rbundler/setup', ''
          ENV['RUBYOPT'] = ENV['RUBYOPT'].sub "-I#{File.expand_path('..', __FILE__)}", ''
        end
	      sh("bundle install --local --without #{(environments - [env]).join(' ')}")
      end
    end
  end
end

namespace "test" do
  ["spec", "spec:rcov", "spec:ci" ].each do |task_name|
    task task_name do
      sh("cd spec && rake #{task_name}")
    end
  end
end
