source "http://rubygems.org"

gem "sinatra"
gem "thin"
gem "uuidtools"

group :test do
  gem "rack-test", :require => "rack/test"
  gem "rspec", :require => ["spec", "spec/interop/test"]
  gem "rcov"
  gem "ci_reporter"
end
