source :rubygems

gem "rake"
gem "sinatra"
gem "thin"
gem "uuidtools"

group :development do
  gem "ruby-debug", :platforms => :ruby_18
  gem "ruby-debug19", :platforms => :ruby_19
end

group :development, :test do
  gem "rack-test"

  gem "ci_reporter"
  gem "rspec"

  gem "rcov", :platforms => :ruby_18
  gem "simplecov", :platforms => :ruby_19
  gem "simplecov-rcov", :platforms => :ruby_19
end
