# Copyright (c) 2009-2012 VMware, Inc.

$:.unshift(File.expand_path("../../rake", __FILE__))

ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../Gemfile", __FILE__)

require "rubygems"
require "bundler"
Bundler.setup(:default, :test)

require "rake"
begin
  require "rspec/core/rake_task"
rescue LoadError
end

require "bundler_task"
require "ci_task"

BundlerTask.new

if defined?(RSpec)
  namespace :spec do
    desc "Run Functional Tests"
    rspec_task = RSpec::Core::RakeTask.new(:functional) do |t|
      t.pattern = "spec/functional/**/*_spec.rb"
      t.rspec_opts = %w(--format progress --colour)
    end

    CiTask.new do |task|
      task.rspec_task = rspec_task
    end
  end
end

desc "Install dependencies and run tests"
task :spec => %w(bundler:install:test spec:functional)
