#!/bin/bash
#
# Copyright (c) 2009-2012 VMware, Inc.

set -e

export PATH=/var/vcap/bosh/bin:$PATH
exec 2>&1
exec /var/vcap/bosh/bin/bosh_agent -c -I $(cat /etc/infrastructure) -n http://vcap:vcap@localhost:6969 -P microcloud
