#!/usr/bin/env ruby
# frozen_string_literal: true

require 'English'

Dir.chdir(File.expand_path(__dir__ + '/../src')) do
  command = 'bundle exec rubocop-git --cached'
  puts("Running '#{command}'")
  system(command)
end

exit $CHILD_STATUS.exitstatus
