#!/usr/bin/env bash

set -e

# assumes targeting director already
# and variables have been exported

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# TODO(db, ja): validate required variables have been set
# STEMCELL_OS
# STEMCELL_VERSION
# BOSH_DEPLOYMENT_PATH
# BOSH_DIRECTOR_RELEASE_PATH
# BOSH_BINARY_PATH


cd src/go
export GOPATH=$(pwd)
export PATH="${GOPATH}/bin":$PATH

cd src/github.com/cloudfoundry/bosh-release-acceptance-tests
go install ./vendor/github.com/onsi/ginkgo/ginkgo
if [[ -n "${FOCUS_SPEC+x}" ]];then
  ginkgo -r -v -race -randomizeSuites -randomizeAllSpecs -focus="${FOCUS_SPEC}" -nodes 5 brats
else
  ginkgo -r -v -race -randomizeSuites -randomizeAllSpecs
fi
