#!/usr/bin/env bash
set -e

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# assumes targeting director already
# and variables have been exported

# TODO(db, ja): validate required variables have been set
# STEMCELL_OS
# STEMCELL_VERSION
# BOSH_DEPLOYMENT_PATH
# BOSH_DIRECTOR_RELEASE_PATH
# BOSH_BINARY_PATH

pushd "${script_dir}/../src/go/src/github.com/cloudfoundry/bosh-release-acceptance-tests" || exit 1
  if [[ -n "${FOCUS_SPEC+x}" ]];then
    go run github.com/onsi/ginkgo/v2/ginkgo -r -v \
      --race --randomize-suites --randomize-all \
      --skip-package=performance \
      --focus="${FOCUS_SPEC}" \
      -nodes 5 \
      brats
  else
    go run github.com/onsi/ginkgo/v2/ginkgo -r -v \
      --race --randomize-suites --randomize-all \
      --skip-package=performance
  fi
popd
