#!/usr/bin/env bash
set -eu -o pipefail
set -x

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# assumes targeting director already
# and variables have been exported

# TODO(db, ja): validate required variables have been set
# STEMCELL_OS
# STEMCELL_VERSION
# BOSH_DEPLOYMENT_PATH
# BOSH_DIRECTOR_RELEASE_PATH
# BOSH_BINARY_PATH

pushd "${script_dir}/../src/brats" || exit 1
  go run github.com/onsi/ginkgo/v2/ginkgo -r -v \
    --race --randomize-suites --randomize-all \
    --skip-package=performance \
    --focus="${FOCUS_SPEC:-}" \
    -nodes 5 \
    .
popd
