require "rubygems"
require "bundler"

gem_helper = Bundler::GemHelper.new(Dir.pwd)

desc "Run specs"
task "spec" => [ "bundler:install:test", "test:spec" ]

desc "Build Bosh Package Compiler gem into the pkg directory"
task "build" do
  gem_helper.build_gem
end

desc "Build and install Bosh Package Compiler gem into system gems"
task "install" do
  sh("bundle install --local --without test development")
  gem_helper.install_gem
end

namespace "bundler" do
  desc "Install gems"
  task "install" do
    sh("bundle install")
  end

  environments = %w(test development production)

  environments.each do |env|
    desc "Install gems for #{env}"
    task "install:#{env}" do
      sh("bundle install --local --without #{(environments - [env]).join(' ')}")
    end
  end
end

namespace "test" do
  ["spec", "spec:rcov", "spec:ci" ].each do |task_name|
    task task_name do
      sh("cd spec && bundle exec rake #{task_name}")
    end
  end
end
