source :rubygems
gemspec

gem "rake"

group :test, :development do
  gem "ci_reporter"
  gem "rspec"

  gem "ruby-debug", :platforms => :ruby_18
  gem "ruby-debug19", :platforms => :ruby_19

  gem "rcov", :platforms => :ruby_18

  gem "simplecov", :platforms => :ruby_19
  gem "simplecov-rcov", :platforms => :ruby_19

  gem "bosh_cli", ">=0.13.7"
end
