---
groups:
  - name: bosh
    jobs:
      - unit-2.4
      - integration-postgres-gocli-sha2
      - upgrade-tests
      - candidate-release-v2

shared:
  - &install-dependencies
    task: install-dependencies
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: bosh/main
      inputs:
      - name: bosh-src
        path: uninstalled-bosh-src
      - name: bosh-cli
      - name: bosh-agent
      outputs:
      - name: bosh-src
      params:
        RUBY_VERSION: 2.4.4
      run:
        path: /bin/bash
        args:
        - -cex
        - |
          mv ./bosh-cli/*bosh-cli-*-linux-amd64 /usr/local/bin/bosh
          chmod +x /usr/local/bin/bosh
          source uninstalled-bosh-src/ci/tasks/utils.sh
          agent_path=uninstalled-bosh-src/src/go/src/github.com/cloudfoundry/
          mkdir -p $agent_path
          cp -r bosh-agent $agent_path
          pushd uninstalled-bosh-src/src
            source /etc/profile.d/chruby.sh
            chruby $RUBY_VERSION

            bundle install --local
            bundle exec rake spec:integration:install_dependencies
          popd
          rsync -a uninstalled-bosh-src/ bosh-src/

  - &deploy-director
    task: deploy-director
    tags: [vsphere-v6.5]
    file: bosh-src/ci/bats/tasks/deploy-director.yml
    params:
      BAT_INFRASTRUCTURE: vsphere
      BOSH_CLIENT:                          ((stemcell-test-director-username))
      BOSH_CLIENT_SECRET:                   ((stemcell-test-director-password))
      BOSH_VSPHERE_VCENTER:                 ((vcenter-ip))
      BOSH_VSPHERE_VCENTER_USER:            ((vcenter-user))
      BOSH_VSPHERE_VCENTER_PASSWORD:        ((vcenter-password))
      BOSH_VSPHERE_VERSION:                 ((vsphere-version))
      BOSH_VSPHERE_VCENTER_DC:              ((vcenter-dc))
      BOSH_VSPHERE_VCENTER_CLUSTER:         ((vcenter-cluster))
      BOSH_VSPHERE_VCENTER_DATASTORE:       ((vcenter-datastore))
      BOSH_VSPHERE_VCENTER_VLAN:            ((vcenter-vlan))
      BOSH_VSPHERE_VCENTER_VM_FOLDER:       ((vcenter-vm-folder))
      BOSH_VSPHERE_VCENTER_TEMPLATE_FOLDER: ((vcenter-template-folder))
      BOSH_VSPHERE_VCENTER_DISK_PATH:       ((vcenter-disk-path))
      BOSH_VSPHERE_VCENTER_RP:              ((vcenter-rp))
      DEPLOY_ARGS: |
        -o bosh-deployment/vsphere/resource-pool.yml
jobs:
  - name: unit-2.4
    public: true
    serial: true
    build_logs_to_retain: 250
    plan:
      - { get: bosh-src, trigger: true }

      - task: test
        timeout: 1h
        file: bosh-src/ci/tasks/test-unit.yml
        params:
          DB: sqlite

  - name: integration-postgres-gocli-sha2
    public: true
    serial: true
    build_logs_to_retain: 250
    plan:
      - aggregate:
        - get: bosh-src
          trigger: true
        - get: bosh-cli
          trigger: true
        - get: bosh-agent
        - get: integration-tests-parallel-runtime

      - <<: *install-dependencies

      - task: tests
        privileged: true
        file: bosh-src/ci/tasks/test-integration-gocli.yml
        tags: ["bosh-integration-1"]
        params:
          DB:           postgresql
          SHA2_MODE:    true

      - put: integration-tests-parallel-runtime
        params:
          file: parallel-runtime-log/parallel_runtime_rspec.log
          acl: public-read

  - name: upgrade-tests
    public: true
    serial: true
    build_logs_to_retain: 250
    plan:
      - aggregate:
        - get: bosh-src
          trigger: true
        - get: bosh-cli
          trigger: true
        - get: bosh-agent
      - aggregate:
        - task: upgrade-with-postgres
          privileged: true
          file: bosh-src/ci/tasks/test-upgrade.yml
          tags: ["bosh-integration-6"]
          params:
            DB: postgresql

        - task: upgrade-with-mysql
          privileged: true
          file: bosh-src/ci/tasks/test-upgrade.yml
          tags: ["bosh-integration-7"]
          params:
            DB: mysql

  - name: candidate-release-v2
    plan:
    - get: bosh-src
      trigger: true
      passed:
      - unit-2.4
      - integration-postgres-gocli-sha2
      - upgrade-tests
    - get: bosh-cli
    - get: candidate-version
      resource: candidate-version-v2
      params:
        bump: major
    - task: make
      file: bosh-src/ci/tasks/make-candidate.yml
    - put: bosh-candidate-release-tarballs
      params:
        file: "release/bosh-dev-release.tgz"
resources:
  - name: bosh-candidate-release-tarballs
    type: s3
    source:
      bucket: bosh-toronto-director-v2
      access_key_id: ((candidate_release_access_key_id))
      secret_access_key: ((candidate_release_secret_access_key))
      versioned_file: "bosh-dev-release.tgz"
      region_name: us-west-1

  - name: candidate-version-v2
    type: semver
    source:
      bucket: bosh-toronto-director-v2
      key: version
      access_key_id: ((candidate_release_access_key_id))
      secret_access_key: ((candidate_release_secret_access_key))
      region_name: us-west-1

  - name: bosh-src
    type: git
    source:
      uri: ((bosh_src_url))
      branch: external-cpi-refactor
      private_key: ((github_deployment_key))

  - name: integration-tests-parallel-runtime
    type: s3
    source:
      bucket: ((integration_runtime_bucket))
      access_key_id: ((integration_runtime_access_key_id))
      secret_access_key: ((integration_runtime_secret_access_key))
      versioned_file: "parallel_runtime_rspec.log"

  - name: bosh-cli
    type: s3
    source:
      regexp: alpha-bosh-cli-(.*)-linux-amd64
      bucket: ((bosh_cli_aws_s3_alpha_release_bucket))
      region_name: ((bosh_cli_aws_s3_release_bucket_region))

  - name: bosh-agent
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-agent
      branch: master
