source :rubygems

gem "rake"
gem "nats"
gem "yajl-ruby", :require => "yajl"
gem "uuidtools"
gem "netaddr"
gem "blobstore_client", "~> 0.3"
gem "posix-spawn"
gem "monit_api"

group :test do
  gem "rcov_analyzer"
  gem "rspec", :require => ["spec", "spec/interop/test"]
  gem "rcov"
  gem "ci_reporter"
end
