source :rubygems

gem "rake"
gem "nats"
gem "uuidtools"
gem "SystemTimer"
gem "yajl-ruby", :require => "yajl"
gem "ruby-debug"
gem "uuidtools"
gem "netaddr"
gem "blobstore_client", "~> 0.3" # 0.2 has streaming support

group :test do
  gem "rcov_analyzer"
  gem "rspec", :require => ["spec", "spec/interop/test"]
  gem "rcov"
  gem "ci_reporter"
end
