source :rubygems

gem "blobstore_client", "~> 0.3.11"
gem "highline"
gem "monit_api"
gem "nats", "=0.4.22.beta.4"
gem "netaddr"
gem "posix-spawn"
gem "rake"
gem "rack-test"
gem "ruby-atmos-pure"
gem "sigar", ">=0.7.0"
gem "sinatra"
gem "thin"
gem "uuidtools"
gem "yajl-ruby", :require => "yajl"

group :development do
  gem "ruby-debug", :platforms => :ruby_18
  gem "ruby-debug19", :platforms => :ruby_19
end

group :development, :test do
  gem "ci_reporter"
  gem "rspec"

  gem "rcov", :platforms => :ruby_18
  gem "simplecov", :platforms => :ruby_19
  gem "simplecov-rcov", :platforms => :ruby_19
end
