# Copyright (c) 2009-2012 VMware, Inc.

$:.unshift(File.expand_path("../../rake", __FILE__))

ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../Gemfile", __FILE__)

require "rubygems"
require "bundler"
Bundler.setup(:default, :test)

require "rake"
require "rake/dsl_definition"
begin
  require "rspec/core/rake_task"
rescue LoadError
end

require "atmos"
require "bundler_task"
require "ci_task"
require "highline/import"
require "json"
require "yaml"

BundlerTask.new

if defined?(RSpec)
  namespace "spec" do
    SPEC_OPTS = %w(--format progress --colour)

    desc "Run unit tests"
    unit_rspec_task = RSpec::Core::RakeTask.new(:unit) do |t|
      t.pattern = "spec/unit/**/*_spec.rb"
      t.rspec_opts = SPEC_OPTS
    end

    CiTask.new do |task|
      task.rspec_task = unit_rspec_task
    end

    desc "Run functional tests"
    fn_rspec_task = RSpec::Core::RakeTask.new(:functional) do |t|
      t.pattern = "spec/functional/**/*_spec.rb"
      t.rspec_opts = SPEC_OPTS
    end

    CiTask.new do |task|
      task.rspec_task = fn_rspec_task
    end

    desc "transitional ci task"
    task "ci" => %w[spec:unit:ci spec:functional:ci]

    namespace :combined do
      task :run => %w(spec:unit spec:functional)
    end

  end
end

# stemcell generation is now in its own file
import "stemcell.rake"
import "stemcell2.rake"
