---
name: bosh
director_uuid: 317b3faa-1cf1-4d67-9011-3ef37dde79e8 # CHANGE: Director UUID

release:
  name: bosh
  version: latest

compilation:
  workers: 3
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: m1.small

update:
  canaries: 1
  canary_watch_time: 3000-120000
  update_watch_time: 3000-120000
  max_in_flight: 4
  max_errors: 1

networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: default
    type: manual
    subnets:
      - name: private
        range: 10.0.1.0/24
        gateway: 10.0.1.1
        reserved:
          - 10.0.1.2 - 10.0.1.9
        static:
          - 10.0.1.10 - 10.0.1.20
        cloud_properties:
          security_groups:
            - default # CHANGE: Security Group
          net_id: 2438bca2-24fa-450f-ae7b-ec2e53b51984 # CHANGE: OpenStack Quantum network UUID

resource_pools:
  - name: small
    network: default
    size: 7
    stemcell:
      name: bosh-stemcell
      version: latest
    cloud_properties:
      instance_type: m1.small

  - name: medium
    network: default
    size: 1
    stemcell:
      name: bosh-stemcell
      version: latest
    cloud_properties:
      instance_type: m1.medium

jobs:
  - name: powerdns
    template: powerdns
    instances: 1
    resource_pool: small
    networks:
      - name: default
        default: [dns, gateway]
        static_ips:
          - 10.0.1.10 # CHANGE: Static IP 1

  - name: nats
    template: nats
    instances: 1
    resource_pool: small
    networks:
      - name: default
        default: [dns, gateway]
        static_ips:
          - 10.0.1.11 # CHANGE: Static IP 2

  - name: postgres
    template: postgres
    instances: 1
    resource_pool: small
    persistent_disk: 2048
    networks:
      - name: default
        default: [dns, gateway]
        static_ips:
          - 10.0.1.12 # CHANGE: Static IP 3

  - name: redis
    template: redis
    instances: 1
    resource_pool: small
    networks:
      - name: default
        default: [dns, gateway]
        static_ips:
          - 10.0.1.13 # CHANGE: Static IP 4

  - name: director
    template: director
    instances: 1
    resource_pool: medium
    persistent_disk: 4096
    networks:
      - name: default
        default: [dns, gateway]
        static_ips:
          - 10.0.1.14 # CHANGE: Static IP 5
      - name: floating
        static_ips:
          - 192.168.1.226 # Change: Floating IP 1

  - name: blobstore
    template: blobstore
    instances: 1
    resource_pool: small
    networks:
      - name: default
        default: [dns, gateway]
        static_ips:
          - 10.0.1.15 # CHANGE: Static IP 6

  - name: registry
    template: registry
    instances: 1
    resource_pool: small
    networks:
      - name: default
        default: [dns, gateway]
        static_ips:
          - 10.0.1.16 # CHANGE: Static IP 7

  - name: health_monitor
    template: health_monitor
    instances: 1
    resource_pool: small
    networks:
      - name: default
        default: [dns, gateway]
        static_ips:
          - 10.0.1.17 # CHANGE: Static IP 8

properties:
  env:

  dns:
    address: 10.0.1.10 # CHANGE: Static IP 1
    user: powerdns
    password: powerdns
    database:
      name: powerdns
    webserver:
      password: powerdns
    replication:
      basic_auth: replication:zxKDUBeCfKYXk
      user: replication
      password: powerdns
    recursor: 10.0.1.5 # CHANGE: microBOSH IP address

  nats:
    address: 10.0.1.11 # CHANGE: Static IP 2
    user: nats
    password: nats

  postgres:
    address: 10.0.1.12 # CHANGE: Static IP 3
    user: postgres
    password: postgres
    database: bosh

  redis:
    address: 10.0.1.13 # CHANGE: Static IP 4
    password: redis

  director:
    name: bosh
    address: 10.0.1.14 # CHANGE: Static IP 5

  blobstore:
    address: 10.0.1.15 # CHANGE: Static IP 6
    agent:
      user: agent
      password: agent
    director:
      user: director
      password: director

  registry:
    address: 10.0.1.16 # CHANGE: Static IP 7
    http:
      user: registry
      password: registry

  hm:
    http:
      user: hm
      password: hm
    director_account:
      user: admin
      password: admin
    event_nats_enabled: false
    email_notifications: false
    tsdb_enabled: false
    pagerduty_enabled: false
    varz_enabled: true

  openstack:
    auth_url: http://192.168.1.1:5000/v2.0 # CHANGE: OpenStack Auth URL
    username: username # CHANGE: OpenStack Username
    api_key: password # CHANGE: OpenStack Password
    tenant: tenant # CHANGE: OpenStack Tenant
    region: # CHANGE: OpenStack Region (optional)
    default_key_name: bosh-key-name # CHANGE: OpenStack default Keyname to use when spinning up new VMs
    default_security_groups: ["default"] # CHANGE: OpenStack default Security Group to use when spinning up new VMs