---
name: bosh-openstack
director_uuid: <director_uuid> # CHANGE

release:
  name: bosh
  version: latest

compilation:
  workers: 3
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: <flavor_name> # CHANGE

update:
  canaries: 1
  canary_watch_time: 3000-120000
  update_watch_time: 3000-120000
  max_in_flight: 4
  max_errors: 1

networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: default
    type: manual
    subnets:
      - name: private
        range: <subnet_cidr> # CHANGE
        gateway: <subnet_gateway> # CHANGE
        reserved:
          - <first_reserved_ip_address> - <last_reserved_ip_address> # CHANGE
        static:
          - <first_ip_address_for_vms> - <last_ip_address_for_vms> # CHANGE
        cloud_properties:
          net_id: <network_uuid> # CHANGE

resource_pools:
  - name: common
    network: default
    size: 8
    stemcell:
      name: bosh-openstack-kvm-ubuntu
      version: latest
    cloud_properties:
      instance_type: <flavor_name> # CHANGE

jobs:
  - name: nats
    template: nats
    instances: 1
    resource_pool: common
    networks:
      - name: default
        default: [dns, gateway]
        static_ips:
          - <ip_address_for_nats> # CHANGE

  - name: redis
    template: redis
    instances: 1
    resource_pool: common
    networks:
      - name: default
        default: [dns, gateway]
        static_ips:
          - <ip_address_for_redis> # CHANGE

  - name: postgres
    template: postgres
    instances: 1
    resource_pool: common
    persistent_disk: 16384
    networks:
      - name: default
        default: [dns, gateway]
        static_ips:
          - <ip_address_for_postgres> # CHANGE

  - name: powerdns
    template: powerdns
    instances: 1
    resource_pool: common
    networks:
      - name: default
        default: [dns, gateway]
        static_ips:
          - <ip_address_for_powerdns> # CHANGE

  - name: blobstore
    template: blobstore
    instances: 1
    resource_pool: common
    networks:
      - name: default
        default: [dns, gateway]
        static_ips:
          - <ip_address_for_blobstore> # CHANGE

  - name: director
    template: director
    instances: 1
    resource_pool: common
    persistent_disk: 16384
    networks:
      - name: default
        default: [dns, gateway]
        static_ips:
          - <ip_address_for_director> # CHANGE
      - name: floating
        static_ips:
          - <allocated_floating_ip_1> # CHANGE

  - name: registry
    template: registry
    instances: 1
    resource_pool: common
    networks:
      - name: default
        default: [dns, gateway]
        static_ips:
          - <ip_address_for_registry> # CHANGE

  - name: health_monitor
    template: health_monitor
    instances: 1
    resource_pool: common
    networks:
      - name: default
        default: [dns, gateway]
        static_ips:
          - <ip_address_for_health_monitor> # CHANGE

properties:
  nats:
    address: <ip_address_for_nats> # CHANGE
    user: nats
    password: nats

  redis:
    address: <ip_address_for_redis> # CHANGE
    password: redis

  postgres: &bosh_db
    host: <ip_address_for_postgres> # CHANGE
    user: postgres
    password: postgres
    database: bosh

  dns:
    address: <ip_address_for_powerdns> # CHANGE
    db: *bosh_db
    recursor: <microbosh_ip_address> # CHANGE

  blobstore:
    address: <ip_address_for_blobstore> # CHANGE
    agent:
      user: agent
      password: agent
    director:
      user: director
      password: director

  director:
    name: bosh
    address: <ip_address_for_director> # CHANGE
    db: *bosh_db
    snapshot_schedule: false
    self_snapshot_schedule: false

  registry:
    address: <ip_address_for_registry> # CHANGE
    db: *bosh_db
    http:
      user: registry
      password: registry

  hm:
    http:
      user: hm
      password: hm
    director_account:
      user: admin
      password: admin
    resurrector_enabled: true

  ntp:
    - 0.north-america.pool.ntp.org
    - 1.north-america.pool.ntp.org

  openstack:
    auth_url: http://<identity_server>:5000/v2.0 # CHANGE
    username: <username> # CHANGE
    api_key: <password> # CHANGE
    tenant: <tenant> # CHANGE
    region: <region> # CHANGE
    default_security_groups: ["default", <microbosh_security_group>] # CHANGE
    default_key_name: <microbosh_keypair> # CHANGE