# Change the following below:
# CHANGE: Director UUID
# CHANGE: Elastic IP 1
# CHANGE: microBOSH IP address
# CHANGE: AWS EC2 access_key_id
# CHANGE: AWS EC2 secret_access_key
# CHANGE: AWS EC2 region
# CHANGE: AWS EC2 default Keyname to use when spinning up new VMs
# CHANGE: AWS EC2 default Security Groups to use when spinning up new VMs
---
name: bosh
director_uuid: 317b3faa-1cf1-4d67-9011-3ef37dde79e8 # CHANGE: Director UUID

release:
  name: bosh
  version: latest

compilation:
  workers: 3
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: m1.small

update:
  canaries: 1
  canary_watch_time: 3000-120000
  update_watch_time: 3000-120000
  max_in_flight: 4
  max_errors: 1

networks:
  - name: elastic
    type: vip
    cloud_properties: {}
  - name: default
    type: dynamic
    cloud_properties:
      security_groups:
        - default # CHANGE: Security Group

resource_pools:
  - name: medium
    network: default
    size: 1
    stemcell:
      name: bosh-aws-xen-ubuntu
      version: latest
    cloud_properties:
      instance_type: m1.medium

jobs:
  - name: core
    template:
    - powerdns
    - nats
    - postgres
    - redis
    - director
    - blobstore
    - registry
    - health_monitor
    instances: 1
    resource_pool: medium
    networks:
      - name: default
        default: [dns, gateway]
      - name: elastic
        static_ips:
          - 54.241.11.212 # CHANGE: Elastic IP 1

properties:
  env:

  postgres: &bosh_db
    user: postgres
    password: postges
    host: 127.0.0.1
    listen_address: 127.0.0.1
    database: bosh

  dns:
    address: 127.0.0.1 # CHANGE: Elastic IP 1
    db: *bosh_db
    user: powerdns
    password: powerdns
    database:
      name: powerdns
    webserver:
      password: powerdns
    replication:
      basic_auth: replication:zxKDUBeCfKYXk
      user: replication
      password: powerdns
    recursor: 54.241.12.225 # CHANGE: microBOSH IP address

  nats:
    address: 127.0.0.1
    user: nats
    password: nats

  redis:
    address: 127.0.0.1
    password: redis

  director:
    name: bosh
    address: 127.0.0.1
    db: *bosh_db

  blobstore:
    address: 127.0.0.1
    agent:
      user: agent
      password: agent
    director:
      user: director
      password: director

  registry:
    address: 127.0.0.1
    db: *bosh_db
    http:
      user: registry
      password: registry

  hm:
    http:
      user: hm
      password: hm
    director_account:
      user: admin
      password: admin
    event_nats_enabled: false
    email_notifications: false
    tsdb_enabled: false
    pagerduty_enabled: false
    varz_enabled: true

  aws:
    access_key_id: aws-access_key # CHANGE: AWS EC2 access_key_id
    secret_access_key: aws-secret_key # CHANGE: AWS EC2 secret_access_key
    region: aws-region # CHANGE: AWS EC2 region
    default_key_name: bosh-key-name # CHANGE: AWS EC2 default Keyname to use when spinning up new VMs
    default_security_groups: ["default"] # CHANGE: AWS EC2 default Security Groups to use when spinning up new VMs