---
name: bosh
director_uuid: 317b3faa-1cf1-4d67-9011-3ef37dde79e8 # CHANGE: Director UUID

release:
  name: bosh
  version: latest

compilation:
  workers: 3
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: m1.small

update:
  canaries: 1
  canary_watch_time: 3000-120000
  update_watch_time: 3000-120000
  max_in_flight: 4

networks:
  - name: elastic
    type: vip
    cloud_properties: {}
  - name: default
    type: dynamic
    cloud_properties:
      security_groups:
        - default # CHANGE: Security Group

resource_pools:
  - name: small
    network: default
    size: 7
    stemcell:
      name: bosh-aws-xen-ubuntu
      version: latest
    cloud_properties:
      instance_type: m1.small

  - name: medium
    network: default
    size: 1
    stemcell:
      name: bosh-aws-xen-ubuntu
      version: latest
    cloud_properties:
      instance_type: m1.medium

jobs:
  - name: powerdns
    template: powerdns
    instances: 1
    resource_pool: small
    networks:
      - name: default
        default: [dns, gateway]
      - name: elastic
        static_ips:
          - 54.241.11.212 # Change: Elastic IP 1

  - name: nats
    template: nats
    instances: 1
    resource_pool: small
    networks:
      - name: default
        default: [dns, gateway]

  - name: postgres
    template: postgres
    instances: 1
    resource_pool: small
    persistent_disk: 2048
    networks:
      - name: default
        default: [dns, gateway]

  - name: redis
    template: redis
    instances: 1
    resource_pool: small
    networks:
      - name: default
        default: [dns, gateway]

  - name: director
    template: director
    instances: 1
    resource_pool: medium
    persistent_disk: 4096
    networks:
      - name: default
        default: [dns, gateway]
      - name: elastic
        static_ips:
          - 54.241.12.117 # Change: Elastic IP 2

  - name: blobstore
    template: blobstore
    instances: 1
    resource_pool: small
    persistent_disk: 51200
    networks:
      - name: default
        default: [dns, gateway]

  - name: registry
    template: registry
    instances: 1
    resource_pool: small
    networks:
      - name: default
        default: [dns, gateway]

  - name: health_monitor
    template: health_monitor
    instances: 1
    resource_pool: small
    networks:
      - name: default
        default: [dns, gateway]

properties:
  env:

  dns:
    address: 54.241.11.212 # Change: Elastic IP 1
    user: powerdns
    password: powerdns
    database:
      name: powerdns
    webserver:
      password: powerdns
    replication:
      basic_auth: replication:zxKDUBeCfKYXk
      user: replication
      password: powerdns
    recursor: 54.241.12.225 # CHANGE: microBOSH IP address

  nats:
    address: 0.nats.default.bosh.microbosh
    user: nats
    password: nats

  postgres:
    address: 0.postgres.default.bosh.microbosh
    user: postgres
    password: postgres
    database: bosh

  redis:
    address: 0.redis.default.bosh.microbosh
    password: redis

  director:
    name: bosh
    address: 0.director.default.bosh.microbosh

  blobstore:
    address: 0.blobstore.default.bosh.microbosh
    agent:
      user: agent
      password: agent
    director:
      user: director
      password: director

  registry:
    address: 0.registry.default.bosh.microbosh
    http:
      user: registry
      password: registry

  hm:
    http:
      user: hm
      password: hm
    director_account:
      user: admin
      password: admin
    event_nats_enabled: false
    email_notifications: false
    tsdb_enabled: false
    pagerduty_enabled: false
    varz_enabled: true

  aws:
    access_key_id: aws-access_key # CHANGE: AWS EC2 access_key_id
    secret_access_key: aws-secret_key # CHANGE: AWS EC2 secret_access_key
    region: aws-region # CHANGE: AWS EC2 region
    default_key_name: bosh-key-name # CHANGE: AWS EC2 default Keyname to use when spinning up new VMs
    default_security_groups: ["default"] # CHANGE: AWS EC2 default Security Group to use when spinning up new VMs
