---
platform: linux

image: docker:///bosh/os-image-stemcell-builder

inputs:
  - name: bosh-src
  - name: bosh-release
  - name: os-image
  - name: version

outputs:
  - name: stemcell

run:
  path: bosh-src/ci/pipelines/stemcell/tasks/build.sh

params:
  IAAS:       replace-me
  HYPERVISOR: replace-me
  OS_NAME:    replace-me
  OS_VERSION: replace-me
