AllCops:
  TargetRubyVersion: 2.5
  Exclude:
  - tmp/**/*

# Layout
Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented


# Metrics
Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 25
  ExcludedMethods: [describe, context, let, it, chdir, shared_examples, shared_examples_for]

Metrics/ClassLength:
  Max: 200

Metrics/LineLength:
  Max: 130

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false



# Style
Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/MultilineBlockChain:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false
