source 'https://rubygems.org'

gem 'bosh-core', path: 'bosh-core'
gem 'bosh-director', path: 'bosh-director'
gem 'bosh-director-core', path: 'bosh-director-core'
gem 'bosh-monitor', path: 'bosh-monitor'
gem 'bosh-nats-sync', path: 'bosh-nats-sync'
gem 'bosh-template', path: 'bosh-template'
gem 'bosh_common', path: 'bosh_common'

gem 'io-stream', '<= 0.4.0' # TODO unpin; v0.4.1 "expected `[#<Socket:(closed)>].empty?` to be truthy, got false"
gem 'mysql2'
gem 'pg'
gem 'sequel', '~> 5.29.0'
gem 'sinatra', '~>2.2.0'
gem 'sinatra-contrib', '~>2.2.0'

group :development, :test do
  gem 'bosh-dev', path: 'bosh-dev'

  gem 'bundle-audit'

  gem 'rspec'
  gem 'rspec-instafail'
  gem 'rspec-its'

  gem 'parallel_tests'

  gem 'rubocop'
  gem 'rubocop-git'

  gem 'simplecov', require: false

  gem 'pry-byebug'
  gem 'pry-remote'

  gem 'async-rspec'
  gem 'blue-shell'
  gem 'factory_bot'
  gem 'fakefs'
  gem 'minitar'
  gem 'rack-test'
  gem 'sqlite3'
  gem 'timecop'
  gem 'webmock'
end
