# encoding: UTF-8
BOSH_REPO_ROOT = File.expand_path(File.join(File.dirname(__FILE__), '..'))
BOSH_SRC_ROOT = File.join(BOSH_REPO_ROOT, 'src')

import 'tasks/fly.rake'
import 'tasks/spec.rake'

task default: :spec

require 'bosh/director/tasks'
