version: "2"

linters:
  default: standard

  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (io.ReadCloser).Close
        - (net.Conn).Close
        - (net.Listener).Close
        - (*os.File).Close
        - (os/exec.Cmd).Wait

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck

formatters:
  enable:
  - goimports
