#!/bin/bash

# Stdout and stderr
echo -n "<%= properties.errand1.stdout * properties.errand1.stdout_multiplier %>"

<% if properties.errand1.run_package_file %>
./packages/errand1/file.sh
<% end %>

echo -n "<%= properties.errand1.stderr * properties.errand1.stderr_multiplier %>" 1>&2

# Log files
mkdir -p sys/log/errand1
echo -n "<%= properties.errand1.logs.stdout %>" > sys/log/errand1/stdout.log
echo -n "<%= properties.errand1.logs.custom %>" > sys/log/custom.log

# Delay
sleep <%= properties.errand1.sleep_duration_in_seconds %>

# Exit code
exit <%= properties.errand1.exit_code %>
