---
name:

logging:
  level: INFO

dir:

network:
  type: dynamic
  cloud_properties: {}

env:
  bosh:
    password:

resources:
  persistent_disk: 4096
  cloud_properties:
    instance_type: m1.small
    availability_zone:

cloud:
  plugin: cloudstack
  properties:
    cloudstack:
      default_security_groups: []
      ssh_user: vcap
    registry:
      endpoint: http://admin:admin@localhost:25889
      user: admin
      password: admin
    agent:
      ntp: []
      blobstore:
        provider: local
        options:
          blobstore_path: /var/vcap/micro_bosh/data/cache
      mbus:

apply_spec:
  properties: {}
  agent:
    blobstore: {}
    nats: {}
