---
resources:
  - name: bosh-src
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh.git
      branch: {{branch}}

jobs:
  - name: start-job
    serial: true
    plan:
      - { get: bosh-src, trigger: false }

  - name: build-centos
    serial: true
    plan:
      - { get: bosh-src, trigger: true, passed: [start-job] }
      - task: build
        file: bosh-src/ci/pipelines/os-image/tasks/build.yml
        config:
          params:
            BOSH_AWS_ACCESS_KEY_ID:     {{aws_access_key}}
            BOSH_AWS_SECRET_ACCESS_KEY: {{aws_secret_key}}
            BOSH_VAGRANT_PRIVATE_KEY:   {{vagrant_private_key}}
            OPERATING_SYSTEM_NAME:      centos
            OPERATING_SYSTEM_VERSION:   7
            OS_IMAGE_S3_BUCKET_NAME:    bosh-os-images
            OS_IMAGE_S3_KEY:            bosh-centos-7-os-image.tgz

  - name: build-ubuntu
    serial: true
    plan:
      - { get: bosh-src, trigger: true, passed: [start-job] }
      - task: build
        file: bosh-src/ci/pipelines/os-image/tasks/build.yml
        config:
          params:
            BOSH_AWS_ACCESS_KEY_ID:     {{aws_access_key}}
            BOSH_AWS_SECRET_ACCESS_KEY: {{aws_secret_key}}
            BOSH_VAGRANT_PRIVATE_KEY:   {{vagrant_private_key}}
            OPERATING_SYSTEM_NAME:      ubuntu
            OPERATING_SYSTEM_VERSION:   trusty
            OS_IMAGE_S3_BUCKET_NAME:    bosh-os-images
            OS_IMAGE_S3_KEY:            bosh-ubuntu-trusty-os-image.tgz
