# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider(:virtualbox) do |v|
    v.name = 'blobstore-client-docker-builder'
    v.customize ['modifyvm', :id, '--cpus', '4']
    v.customize ['modifyvm', :id, '--memory', '4096']
  end

  config.vm.provision :shell do |shell|
    shell.inline = <<-BASH
      apt-get -y update
    BASH
  end

  config.vm.provision('docker')
end
